In [1]:
# Importing pandas library
import pandas as pd

In [2]:
# Read the dataset
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
# display the dataset
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
# Handle categorical data
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [5]:
# Display the columns in the dataset
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
# Assign input values
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [7]:
# Assign output values
dependent=dataset[["charges"]]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [8]:
# Split training and test data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(independent, dependent, test_size=0.20, random_state=0)

In [9]:
#Standardization

In [11]:
# Applying standardization (preprocessing) for input training and test data
from sklearn.preprocessing import StandardScaler
scx=StandardScaler()
# Preprocessing input training/test data
X_train_pre=scx.fit_transform(X_train) 
X_test_pre=scx.transform(X_test) # No need to use fit_transform for preprocessing input test data since the sc variable is already holding the preprocessing logic.

scy=StandardScaler()
# Preprocessing output training/test data
Y_train_pre=scy.fit_transform(Y_train) 
Y_test_pre=scy.transform(Y_test) # No need to use fit_transform for preprocessing input test data since the sc variable is already holding the preprocessing logic.

In [12]:
X_train, X_train_pre, X_test, X_test_pre

(      age  bmi  children  sex_male  smoker_yes
 621    37   34         4         1           1
 194    18   34         0         1           0
 240    23   36         2         0           1
 1168   32   35         2         1           0
 1192   58   32         1         0           0
 ...   ...  ...       ...       ...         ...
 763    27   26         0         1           0
 835    42   35         2         1           0
 1216   40   25         0         1           0
 559    19   35         0         1           0
 684    33   18         1         0           0

 [1070 rows x 5 columns],
 array([[-0.14853305,  0.60616004,  2.41394802,  1.01506676,  1.97125461],
        [-1.49780784,  0.60616004, -0.89219519,  1.01506676, -0.50729114],
        [-1.14273553,  0.92836135,  0.76087642, -0.98515688,  1.97125461],
        ...,
        [ 0.06451033, -0.84374587, -0.89219519,  1.01506676, -0.50729114],
        [-1.42679338,  0.7672607 , -0.89219519,  1.01506676, -0.50729114],
        [-0.4325909 , -1.97145047, -0.06565939, -0.98515688, -0.50729114]],
       shape=(1070, 5)),
       age  bmi  children  sex_male  smoker_yes
 578    52   30         1         1           0
 610    47   29         1         0           0
 569    48   40         2         1           1
 1034   61   38         0         1           0
 198    51   18         0         0           0
 ...   ...  ...       ...       ...         ...
 1084   62   30         2         0           0
 726    41   28         1         1           0
 1132   57   40         0         1           0
 725    30   39         3         0           1
 963    46   24         3         1           0

 [268 rows x 5 columns],
 array([[ 0.91668389, -0.03824259, -0.06565939,  1.01506676, -0.50729114],
        [ 0.56161157, -0.19934324, -0.06565939, -0.98515688, -0.50729114],
        [ 0.63262604,  1.57276398,  0.76087642,  1.01506676,  1.97125461],
        ...,
        [ 1.2717562 ,  1.57276398, -0.89219519,  1.01506676, -0.50729114],
        [-0.64563429,  1.41166332,  1.58741222, -0.98515688,  1.97125461],
        [ 0.49059711, -1.00484653,  1.58741222,  1.01506676, -0.50729114]],
       shape=(268, 5)))

In [13]:
Y_train, Y_train_pre, Y_test, Y_test_pre

(      charges
 621     40182
 194      1137
 240     38511
 1168     4670
 1192    13019
 ...       ...
 763      3070
 835      7160
 1216     5415
 559      1646
 684      4766

 [1070 rows x 1 columns],
 array([[ 2.25340816],
        [-1.0075279 ],
        [ 2.11385062],
        ...,
        [-0.65024055],
        [-0.96501756],
        [-0.70444333]], shape=(1070, 1)),
       charges
 578      9724
 610      8547
 569     45702
 1034    12950
 198      9644
 ...       ...
 1084    15019
 726      6664
 1132    20709
 725     40932
 963      9500

 [268 rows x 1 columns],
 array([[-2.90364169e-01],
        [-3.88664124e-01],
        [ 2.71442409e+00],
        [-2.09371044e-02],
        [-2.97045559e-01],
        [-7.26658956e-01],
        [-9.18915962e-01],
        [-1.47382416e-01],
        [-4.73016676e-01],
        [-6.49405381e-01],
        [-5.38494301e-01],
        [-2.26139304e-01],
        [-4.89720152e-01],
        [-7.52966930e-01],
        [ 4.26716046e-01],
        [-2.08684172e-01],
        [-5.65990252e-02],
        [-8.11011509e-01],
        [-5.63215446e-01],
        [ 1.69325710e+00],
        [ 8.99173859e-01],
        [-4.65769397e-02],
        [ 8.22170836e-01],
        [ 8.23841183e-01],
        [-9.62679069e-01],
        [-7.12711554e-01],
        [-7.90800303e-01],
        [-4.60906656e-01],
        [-7.88795886e-01],
        [-3.99855452e-01],
        [-4.29420605e-01],
        [ 2.98735888e+00],
        [-1.85151004e-02],
        [ 6.20476366e-01],
        [ 1.14444567e-01],
        [-7.56975765e-01],
        [-4.05367599e-01],
        [ 3.17310153e+00],
        [ 2.23845855e+00],
        [-9.45474489e-01],
        [-6.46649307e-01],
        [-8.63042836e-01],
        [ 5.80304506e-01],
        [ 2.86425427e+00],
        [ 1.91658257e+00],
        [ 1.07046800e+00],
        [ 5.46897555e-01],
        [-5.22876552e-01],
        [-7.08452167e-01],
        [ 7.50930511e-01],
        [-8.60370280e-01],
        [ 4.70813223e-01],
        [ 8.65850425e-01],
        [ 2.76060920e+00],
        [ 9.20888377e-01],
        [-8.29552367e-01],
        [-9.08559807e-01],
        [-3.65279258e-01],
        [ 1.06677451e-01],
        [-7.40728903e-03],
        [-9.97839885e-01],
        [ 2.79927775e+00],
        [ 5.99912357e-02],
        [-2.98214802e-01],
        [-2.05844581e-01],
        [-2.77335458e-01],
        [ 1.61583649e+00],
        [ 2.13347720e+00],
        [-8.36901896e-01],
        [-4.20818315e-01],
        [-1.33370229e-02],
        [-1.37527365e-01],
        [ 2.53166933e-01],
        [ 5.73186796e-02],
        [-1.57590269e-02],
        [ 1.36203576e-03],
        [-5.05588454e-01],
        [-4.56814305e-01],
        [ 5.92581561e-01],
        [ 2.85648715e+00],
        [-1.28841558e-01],
        [ 2.72787039e+00],
        [-9.30858947e-01],
        [-4.81034345e-01],
        [ 2.32456496e+00],
        [ 4.82004551e-01],
        [-8.17692899e-01],
        [-8.77073755e-01],
        [-7.24673272e-02],
        [ 1.97404253e+00],
        [-5.73488083e-01],
        [-2.49440653e-01],
        [ 3.90636539e-01],
        [-3.91336680e-01],
        [-7.25155643e-01],
        [-6.72539695e-01],
        [ 2.43054852e+00],
        [ 2.15452358e+00],
        [-6.57590084e-01],
        [-2.17035910e-01],
        [-9.50151462e-01],
        [-6.53414215e-01],
        [-7.39270080e-01],
        [ 2.04962575e+00],
        [ 1.63579714e+00],
        [-8.22453390e-01],
        [-2.19123845e-01],
        [-8.05499362e-01],
        [-1.04955588e-01],
        [ 3.28969180e+00],
        [-6.06078594e-02],
        [-7.46202023e-01],
        [-3.30034924e-01],
        [ 1.71472106e+00],
        [ 2.96272126e+00],
        [-4.56981340e-01],
        [-9.38459029e-01],
        [-3.97266414e-01],
        [-7.12980839e-02],
        [-3.25692020e-01],
        [ 2.41559891e+00],
        [-2.68065029e-01],
        [ 9.33981873e-02],
        [-6.49154828e-01],
        [-4.65583630e-01],
        [-6.92750900e-01],
        [ 8.51903022e-01],
        [ 6.59562499e-01],
        [ 2.92079553e+00],
        [-9.42384346e-01],
        [-4.16057824e-01],
        [-9.58419683e-01],
        [-6.03387305e-01],
        [-3.20680977e-01],
        [ 7.46921677e-01],
        [ 1.86162813e+00],
        [ 5.27354488e-01],
        [-2.58377013e-01],
        [ 8.38790794e-01],
        [-8.69557191e-01],
        [-9.13654367e-01],
        [-2.17704049e-01],
        [-3.25441468e-01],
        [-2.30983312e-01],
        [-6.93753109e-01],
        [ 9.28970830e-02],
        [ 1.25996894e+00],
        [ 1.02334547e-01],
        [-9.66604386e-01],
        [ 1.02862580e+00],
        [-5.55030742e-01],
        [ 2.20571973e+00],
        [-2.70319998e-01],
        [-9.58837269e-01],
        [-8.74484717e-01],
        [-5.59624198e-01],
        [-8.81750729e-01],
        [-9.58920787e-01],
        [-1.76697016e-01],
        [-2.57708874e-01],
        [-6.97761943e-01],
        [-1.82645483e-02],
        [ 1.31308599e+00],
        [-3.18175456e-01],
        [-7.22984191e-01],
        [ 3.27998505e-01],
        [ 5.37274323e-02],
        [-5.91945424e-01],
        [-7.31586481e-01],
        [-9.66103281e-01],
        [-7.63573638e-01],
        [-7.32087586e-01],
        [-4.08457742e-01],
        [-9.36621647e-01],
        [-7.46703127e-01],
        [-7.26324887e-01],
        [-7.32672207e-01],
        [-5.91611354e-01],
        [ 1.41840140e+00],
        [-9.59839478e-01],
        [-1.68178243e-01],
        [-5.34903054e-01],
        [-1.54063806e-01],
        [-8.93860749e-01],
        [ 1.18380109e+00],
        [ 1.24443470e+00],
        [-9.14238989e-01],
        [-8.85592528e-01],
        [ 1.24550170e-01],
        [-2.36411942e-01],
        [ 2.32982656e+00],
        [-7.70004476e-01],
        [-6.45480064e-01],
        [ 6.70002171e-01],
        [-8.90854123e-01],
        [-9.37790890e-01],
        [-5.67474832e-01],
        [-5.55364812e-01],
        [-7.63573638e-01],
        [-7.48122922e-01],
        [-1.41035095e-01],
        [ 2.81355922e+00],
        [-7.78959568e-02],
        [ 5.00962996e-01],
        [-7.32254620e-01],
        [ 2.48617109e+00],
        [ 8.38540242e-01],
        [-3.39138318e-01],
        [-6.15079738e-01],
        [-1.00652569e+00],
        [-3.70457335e-01],
        [ 7.03473907e-02],
        [-6.58842844e-01],
        [-2.00917056e-01],
        [-5.77830987e-01],
        [-9.38041442e-01],
        [-5.39078923e-01],
        [-6.55335114e-01],
        [ 6.68396608e-02],
        [-5.28138146e-01],
        [-5.85013481e-01],
        [-4.35517373e-01],
        [-4.11213816e-01],
        [-8.34730444e-01],
        [-1.12973256e-01],
        [ 8.42947930e-02],
        [-7.81465089e-02],
        [-1.13891947e-01],
        [-5.46929557e-01],
        [-9.24010522e-01],
        [-1.00802901e+00],
        [-4.05785186e-01],
        [-7.99003739e-02],
        [-7.21564396e-01],
        [ 3.69590159e-01],
        [-5.28305181e-01],
        [-3.13498483e-01],
        [ 1.75831714e+00],
        [-5.95787223e-01],
        [-1.22911824e-01],
        [-6.52913111e-01],
        [ 2.02649144e+00],
        [-4.86880561e-01],
        [-4.90722361e-01],
        [-4.00106005e-01],
        [-2.28811860e-01],
        [-8.28633676e-01],
        [-4.57148374e-01],
        [-8.74401199e-01],
        [-5.29724977e-01],
        [ 5.27855592e-01],
        [ 2.84830245e+00],
        [-7.69503371e-01],
        [-8.32057888e-01],
        [-4.90889395e-01],
        [-9.60173547e-01],
        [-4.80700275e-01],
        [-9.66437351e-01],
        [-6.95172904e-01],
        [-8.05081775e-01],
        [-3.83820116e-01],
        [ 9.45358969e-01],
        [ 2.71509223e+00],
        [ 1.51860353e-01],
        [-5.45927348e-01],
        [ 6.27074238e-01],
        [ 2.31604619e+00],
        [-3.09072062e-01]]))

In [14]:
# Using SVM regression algorithm to train the Preprocessed input and output
from sklearn.svm import SVR
regressor=SVR(kernel="rbf",C=1000)  
regressor.fit(X_train_pre, Y_train_pre)  # X_train & Y_train is preprocessed data 
regressor

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1000)

In [15]:
# Prediction based on preprocessed input test data
Y_Pred=regressor.predict(X_test_pre)
Y_Pred

array([-2.75648290e-01, -2.88463351e-01,  2.61978429e+00,  4.82495003e-02,
       -2.56035536e-01, -6.78178619e-01, -9.39014221e-01, -8.65971200e-02,
       -5.03355343e-01, -7.14950930e-01, -4.50431281e-01, -1.58556461e-01,
       -4.03137598e-01, -6.97565209e-01,  4.57737348e-01, -1.84585264e-01,
        7.04214201e-03, -7.69737586e-01, -4.87524785e-01,  9.55008141e-01,
        8.34121905e-01,  4.29674397e-02, -2.07434800e-01,  9.85534901e-01,
       -8.65349560e-01, -6.57299035e-01, -1.05084510e+00, -5.00112646e-01,
       -7.16015132e-01, -3.36646255e-01, -4.45903217e-01,  3.09475606e+00,
        8.15689465e-02, -1.56443328e-01,  4.99546198e-01, -7.21267526e-01,
       -3.67762044e-01,  2.16114420e+00,  1.90188993e+00, -8.50953405e-01,
       -7.63096267e-01, -7.64966020e-01,  1.36023352e+00,  2.95817973e+00,
        1.95864724e+00, -7.69279294e-01, -1.48861238e-01, -5.33969952e-01,
       -6.11559759e-01, -3.65146486e-02, -8.53595910e-01, -7.72929296e-01,
        1.56356066e+00,  2.57218629e+00, -2.09380023e-02, -7.68730027e-01,
       -8.04804863e-01, -3.02467835e-01, -2.70069059e-01,  8.80409249e-02,
       -9.01915317e-01,  2.33064192e+00,  8.74075471e-02, -1.57048104e-01,
       -1.33479347e-01, -1.83705235e-01,  9.73864495e-01,  2.37382723e+00,
       -7.04960681e-01, -4.96156061e-01,  2.64638795e-02, -1.15288178e-01,
        2.14003086e-01, -2.94625224e-03,  5.22518340e-02,  2.13911992e-02,
       -4.16155617e-01, -3.62350769e-01,  3.79001292e-01,  3.19865859e+00,
       -9.81653055e-02,  5.68686335e+00, -8.64315111e-01, -4.52857945e-01,
        2.39014676e+00,  3.12053170e-01, -9.65781383e-01, -8.08081458e-01,
       -1.26099878e-02,  2.08380422e+00, -5.43179923e-01, -1.50679095e-01,
       -9.54335064e-01, -3.18546528e-01, -6.60376864e-01, -6.34620840e-01,
        1.86578337e+00,  1.77373383e+00, -6.80102749e-01, -1.23403235e-01,
       -8.51110178e-01, -5.84015128e-01, -7.23534871e-01,  2.25727981e+00,
        1.25010735e+00, -7.93492232e-01, -1.70587635e-01, -7.93345351e-01,
       -5.15573263e-02,  2.10009124e+00, -2.90236559e-02, -7.98392215e-01,
       -2.57008226e-01,  1.27938569e+00,  3.17436957e+00, -3.93932205e-01,
       -8.45555767e-01, -3.02467835e-01,  4.69271698e-02, -1.04417616e-01,
        3.12371838e+00, -2.31679870e-01,  1.08202926e-01, -5.02580481e-01,
       -3.72415777e-01, -5.69012470e-01,  8.44775124e-01,  5.96911742e-01,
        2.87505867e+00, -8.82403799e-01, -3.60360670e-01, -8.65859618e-01,
       -5.25824648e-01, -3.03300239e-01,  2.25554317e+00,  1.52827457e+00,
        1.43770238e+00, -2.28475670e-01,  6.93419220e-01, -7.87187041e-01,
       -8.45489284e-01, -1.56953397e-01, -2.11678834e-01, -1.78966321e-01,
       -6.24191723e-01, -1.25650941e-02,  9.04048035e-02, -6.71920921e-01,
       -9.17173423e-01, -2.33931012e-01, -5.20985768e-01,  2.34888275e+00,
       -2.57035708e-01, -8.63315420e-01, -9.02741247e-01, -4.80640941e-01,
       -8.27645817e-01, -8.60958266e-01, -1.84585264e-01, -3.49259348e-01,
       -7.33211204e-01,  8.16398293e-02,  4.87146422e-02, -3.09641917e-01,
       -7.93116141e-01, -2.26991895e-01,  2.67005980e-01, -5.52243376e-01,
       -6.62417621e-01, -8.67153957e-01, -6.79844426e-01, -6.42586951e-01,
       -3.98642876e-01, -8.38391399e-01, -7.70752319e-01, -2.03011433e-01,
       -7.13666432e-01, -5.62002548e-01,  2.03107187e+00, -9.25935257e-01,
       -9.49274842e-02, -6.56585650e-01, -8.47054190e-02, -7.89367412e-01,
       -6.33291998e-01,  4.97233786e-01, -8.63564558e-01, -8.01560728e-01,
       -2.04533301e-02, -1.89652064e-01,  2.44059681e+00, -6.88193315e-01,
       -5.41621466e-01,  1.44382016e+00, -8.21998195e-01, -8.40025952e-01,
       -5.04068747e-01, -5.30471294e-01, -6.83051490e-01, -6.71362282e-01,
       -9.33883901e-02,  2.43281978e+00,  2.62597935e-03,  3.10412077e-01,
       -6.33306593e-01,  2.71902856e+00, -7.06540705e-01, -2.44811027e-01,
       -5.49374498e-01, -9.26141558e-01, -3.42227975e-01, -2.98237010e-02,
       -7.00076843e-01, -8.35802774e-01, -5.44029680e-01, -8.39936501e-01,
       -6.14843696e-01, -5.59306527e-01, -6.21029267e-03, -3.69215618e-01,
       -4.72968529e-01, -4.81401689e-01, -3.10665365e-01, -7.77477817e-01,
       -1.12145650e-01,  1.44830689e-01,  5.18018180e-02, -1.68594130e-02,
       -5.69601996e-01, -8.25367758e-01, -9.07057360e-01, -4.26832385e-01,
       -8.79334740e-02,  5.87665046e-01, -5.81520745e-01, -4.25433804e-01,
       -2.56266803e-01,  1.23732960e+00, -5.83312986e-01, -1.55497230e-01,
       -5.91668202e-01,  3.32381787e+00, -3.37632152e-01, -4.71047770e-01,
       -5.21234103e-01, -2.18806290e-01, -7.49402159e-01, -4.02279906e-01,
       -8.23044061e-01, -5.38327701e-01,  9.40958719e-01,  3.01664722e+00,
       -7.53296078e-01, -1.00137616e+00, -8.96762114e-01, -9.41035555e-01,
       -3.99737472e-01, -8.57197706e-01, -6.76950843e-01, -6.63821272e-01,
       -2.96582169e-01,  1.04808204e+00,  2.06098590e+00,  1.10917724e-01,
       -5.44029680e-01, -8.91285549e-02,  8.37347099e-01, -6.38790445e-02])

In [16]:
# Evaluate performance 
from sklearn.metrics import r2_score
r_score=r2_score(Y_test_pre,Y_Pred)
r_score

0.8242906357883337

In [26]:
# Import library to save Python objects to a file and load them 
import pickle
filename="finalized_model_svr_1.sav"

In [27]:
pickle.dump(regressor, open(filename,'wb'))

In [33]:
filename_scx="Standardized_Input.sav"
pickle.dump(scx, open(filename_scx,'wb'))

filename_scy="Standardized_Output.sav"
pickle.dump(scy, open(filename_scy,'wb'))

In [28]:
# Preprocessing user input using already trained input data
preinput=scx.transform([[52,30.2,1,1,0]])
preinput

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[ 0.91668389, -0.00602245, -0.06565939,  1.01506676, -0.50729114]])

In [35]:
# testing. No need to have the load method in the model training file
loaded_model=pickle.load(open("finalized_model_svr_1.sav", 'rb'))
result=loaded_model.predict(preinput)
result
preoutput=scy.inverse_transform([result])
preoutput

array([[9955.72392405]])