In [1]:
import pandas as pd

In [4]:
dataset=pd.read_csv("insurance_pre.csv")

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [8]:
dataset=dataset.astype(int)

In [9]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [11]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [12]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [14]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(independent, dependent, test_size=0.20, random_state=0)

In [21]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=50, random_state=0)
regressor.fit(X_train, Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(n_estimators=50, random_state=0)

In [22]:
Y_pred=regressor.predict(X_test)

In [25]:
Y_pred

array([10706.9       , 10606.65      , 44747.86      , 13192.32      ,
        9975.2       , 14644.94      ,  1761.86      , 10820.54      ,
        6923.81333333,  5226.72      ,  8228.72      , 18044.88      ,
       13421.27      ,  5732.46      , 19904.00666667, 11813.24      ,
       12548.41      ,  5947.72333333,  7003.01333333, 33580.45      ,
       24143.76      , 12799.23      , 11409.64      , 25109.12      ,
        5355.19134921,  5339.2       ,  7329.11333333,  7928.72      ,
        3721.08      ,  9777.02      ,  7784.2       , 48079.68      ,
       14324.68      , 11077.28      , 17231.38      ,  3541.56      ,
        8980.94      , 37722.94      , 39708.36      ,  2363.27      ,
       11472.49333333,  3630.125     , 20281.92      , 46575.44      ,
       36559.22      ,  4042.36      , 15279.52      ,  6732.5       ,
        4639.46      , 11827.8       ,  3122.98333333, 12117.9       ,
       25191.53      , 48786.92      , 11819.90666667,  9645.36      ,
        3093.42      , 10963.56      ,  9060.46      , 17468.2       ,
        1551.13766667, 47306.3       , 16187.18333333, 18626.98      ,
       15064.42      ,  9790.82      , 33580.45      , 41642.38      ,
        5401.3       , 11174.18      , 18938.80566667, 12420.4       ,
       19580.34      , 13921.4       , 12946.28      , 14408.47571429,
        9060.24      , 14479.28      , 19075.62      , 48287.92      ,
       11577.46266667, 48113.94      ,  5810.15301587, 10857.64      ,
       40239.74      , 19031.54      ,  4608.18      ,  4030.55833333,
       14127.24      , 38789.96      ,  5792.92      , 11278.99      ,
        2834.455     , 15340.        ,  5375.94      ,  4449.1       ,
       45586.3       , 45685.16      ,  4982.26      , 10784.18133333,
        3591.24666667,  5903.10666667,  9141.77      , 39800.5       ,
       30499.        ,  3498.9       , 11194.24      ,  4163.806     ,
       11646.4       , 45489.78      , 12429.22      ,  8297.64      ,
       10436.71      , 34034.99      , 47607.25      ,  7154.8       ,
        2939.78      , 10963.56      , 27510.72      ,  9526.2       ,
       41554.3       , 13111.2       , 14675.36      ,  6896.5       ,
       12142.799     ,  5333.1       , 23826.39      , 26097.06      ,
       48112.1       ,  1945.70333333, 19540.72      ,  4031.93033333,
        5846.84      ,  9124.72      , 45947.98      , 43518.96      ,
       23176.64      , 16286.56      , 23201.64      ,  5999.32      ,
        2155.4       , 13432.78      , 10116.42      , 10923.76      ,
        7275.41166667, 14234.32      , 27180.2       , 11757.12      ,
        1497.052     , 11524.16      ,  6060.44      , 39581.72      ,
       10350.94      , 10174.99366667,  4507.53      ,  6682.24      ,
        6006.11833333,  8239.06      , 11813.24      , 11293.71333333,
        9778.12      , 13210.42      , 15385.93333333,  9110.88      ,
        5352.9       ,  9309.72      , 15218.54      ,  5907.44      ,
        4264.24      ,  3296.31733333,  8156.68      ,  4287.78      ,
       11167.94      ,  2158.03      , 12219.36      , 10233.12      ,
        4722.32      ,  6693.36      , 28334.82      ,  1668.43666667,
       19189.57033333,  6997.78888889, 11306.26      ,  8355.212     ,
        9306.66666667, 27821.62      ,  7053.62134921,  3064.7       ,
       14254.1       , 11138.06      , 41166.52      ,  5362.92      ,
        5505.44966667, 23909.78      ,  2930.29      ,  2847.44      ,
        7050.61555556,  6225.48      ,  9585.62      ,  4216.56      ,
       11785.04      , 47072.22      , 17057.12      , 18549.12      ,
        8408.58      , 42687.68      ,  5999.98      , 10622.86      ,
        6523.56      ,  2009.74333333,  9890.56      , 13624.62      ,
        6185.58      ,  4148.722     ,  6532.56833333,  5544.66      ,
        7187.96222222,  7637.31      , 13949.07      ,  6679.91333333,
       10103.34      ,  7873.42      , 11597.68      ,  9120.32      ,
       12188.2       , 14981.86      , 18917.02      , 11971.68      ,
        7044.3       ,  2764.36      ,  5463.631     ,  8256.5       ,
       14260.08      ,  6459.94666667,  4699.06      ,  7194.24      ,
       12260.44      , 34257.45      ,  5574.98      , 11391.        ,
        5897.2       , 37845.31333333,  8366.54      ,  6957.8       ,
       12167.84      , 17859.62      ,  5771.56      ,  8802.72      ,
        2302.59333333,  6656.965     , 19772.7       , 46999.5       ,
        5218.33      ,  5604.26      ,  3083.57566667,  1648.21      ,
        9161.37      ,  2998.44666667,  9102.78      ,  9597.46      ,
        8805.21      , 24697.46      , 46364.16      , 17589.36      ,
        6532.56833333, 11242.012     , 46058.54      ,  9675.32      ])

In [26]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test, Y_pred)
r_score

0.8666048997930276

In [28]:
from sklearn.ensemble import RandomForestRegressor
regressor_1=RandomForestRegressor(n_estimators=100, criterion='squared_error', max_depth=10, random_state=0)
regressor_1.fit(X_train, Y_train)
Y_pred_1=regressor_1.predict(X_test)
from sklearn.metrics import r2_score
r_score_1=r2_score(Y_test, Y_pred_1)
r_score_1

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8746551354890264

In [29]:
from sklearn.ensemble import RandomForestRegressor
regressor_2=RandomForestRegressor(n_estimators=100, criterion='absolute_error', max_depth=10, random_state=0)
regressor_2.fit(X_train, Y_train)
Y_pred_2=regressor_2.predict(X_test)
from sklearn.metrics import r2_score
r_score_2=r2_score(Y_test, Y_pred_2)
r_score_2

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.887073000165453

In [30]:
from sklearn.ensemble import RandomForestRegressor
regressor_3=RandomForestRegressor(n_estimators=100, criterion='poisson', max_depth=10, random_state=0)
regressor_3.fit(X_train, Y_train)
Y_pred_3=regressor_3.predict(X_test)
from sklearn.metrics import r2_score
r_score_3=r2_score(Y_test, Y_pred_3)
r_score_3

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8773030794426256

In [31]:
from sklearn.ensemble import RandomForestRegressor
regressor_4=RandomForestRegressor(n_estimators=100, criterion='poisson', max_depth=50, random_state=0)
regressor_4.fit(X_train, Y_train)
Y_pred_4=regressor_4.predict(X_test)
from sklearn.metrics import r2_score
r_score_4=r2_score(Y_test, Y_pred_4)
r_score_4

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8725459695393039

In [34]:
from sklearn.ensemble import RandomForestRegressor
regressor_4=RandomForestRegressor(n_estimators=100, criterion='poisson', max_depth=5, random_state=0)
regressor_4.fit(X_train, Y_train)
Y_pred_4=regressor_4.predict(X_test)
from sklearn.metrics import r2_score
r_score_4=r2_score(Y_test, Y_pred_4)
r_score_4

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8955097801966453

In [36]:
from sklearn.ensemble import RandomForestRegressor
regressor_4=RandomForestRegressor(n_estimators=100, criterion='squared_error', max_depth=5, max_features=5, random_state=0)
regressor_4.fit(X_train, Y_train)
Y_pred_4=regressor_4.predict(X_test)
from sklearn.metrics import r2_score
r_score_4=r2_score(Y_test, Y_pred_4)
r_score_4

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8954436383936902

In [40]:
from sklearn.ensemble import RandomForestRegressor
regressor_4=RandomForestRegressor(n_estimators=100, criterion='squared_error', max_depth=5, max_features=5, min_samples_split=5, random_state=0)
regressor_4.fit(X_train, Y_train)
Y_pred_4=regressor_4.predict(X_test)
from sklearn.metrics import r2_score
r_score_4=r2_score(Y_test, Y_pred_4)
r_score_4

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8954882499619259

In [41]:
from sklearn.ensemble import RandomForestRegressor
regressor_4=RandomForestRegressor(n_estimators=100, criterion='squared_error', max_depth=5, max_features=5, min_samples_split=5,bootstrap=True, random_state=0)
regressor_4.fit(X_train, Y_train)
Y_pred_4=regressor_4.predict(X_test)
from sklearn.metrics import r2_score
r_score_4=r2_score(Y_test, Y_pred_4)
r_score_4

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8954882499619259

In [42]:
from sklearn.ensemble import RandomForestRegressor
regressor_4=RandomForestRegressor(n_estimators=100, criterion='squared_error', max_depth=5, max_features=5, min_samples_split=5,bootstrap=True, random_state=10)
regressor_4.fit(X_train, Y_train)
Y_pred_4=regressor_4.predict(X_test)
from sklearn.metrics import r2_score
r_score_4=r2_score(Y_test, Y_pred_4)
r_score_4

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8970182967451767

In [49]:
from sklearn.ensemble import RandomForestRegressor
regressor_4=RandomForestRegressor(n_estimators=100, criterion='squared_error', max_depth=5, max_features=5, min_samples_split=5,bootstrap=True, random_state=42)
regressor_4.fit(X_train, Y_train)
Y_pred_4=regressor_4.predict(X_test)
from sklearn.metrics import r2_score
r_score_4=r2_score(Y_test, Y_pred_4)
r_score_4

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8951552837653495