In [98]:
import pandas as pd

In [99]:
dataset=pd.read_csv("insurance_pre.csv")

In [100]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [101]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [102]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [103]:
dependent=dataset[["charges"]]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [104]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [105]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(independent, dependent, test_size=0.20, random_state=0)

In [106]:
from sklearn.svm import SVR
regressor=SVR(kernel="linear")  
regressor.fit(X_train, Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(kernel='linear')

In [107]:
Y_Pred=regressor.predict(X_test)

In [108]:
Y_Pred

array([10692.71762344,  9422.35870607, 10075.3271818 , 12828.50807213,
       10260.62908361,  5660.97717475,  1446.21316475, 10973.79023738,
        7518.64883426,  5589.23450377,  6472.73704656, 10476.94182574,
        8355.76762344,  5449.68959639,  4000.28322885, 10722.18195393,
       12588.1794041 ,  3756.11571459,  7210.52877016,  2129.98896246,
       10905.3494682 , 12063.66889836, 10504.71762344,  9396.11857787,
        2438.64469607,  5346.60265902,  4129.61029443,  8046.30456787,
        4914.51411918,  9075.18322885,  8055.70424738, 12757.57272312,
       13097.03577869, 11230.5013841 ,  3276.3794041 ,  4644.10647672,
        9326.7915123 ,  4500.8915123 ,  8018.18450377,  1966.34915475,
        6259.03258787,  4316.45870607,  7203.81634852, 12749.32463197,
        1646.41380574,  2732.87686131, 10724.06188984,  8033.75966049,
        4904.38609213, 12100.11602803,  2764.41253082,  2457.98099951,
        9848.88641262, 11190.91030148, 12083.92495246,  4034.7714482 ,
        3501.47590689,  9917.94182574,  9298.28736705, 12837.1794041 ,
        1648.10106361, 14076.19533   , 13318.25998098, 10404.66221033,
       10363.72686131, 10470.15042967,  1863.3411918 ,  5802.59469607,
        2753.55615623,  8239.94437557, 12908.30743115, 12031.59628443,
        2135.62877016, 13426.56348525, 12649.1794041 , 12643.53959639,
        8858.87048672,  8808.5354582 ,  6982.40074311, 13300.26794393,
       11575.06857787,  8293.80871312,  2440.52463197,  8826.18322885,
        8504.36794393,  6370.45743115,  3798.31635557,  3508.99565049,
       12564.89182574,  4787.06698951,  5905.60265902, 11245.54087131,
        3284.54852082,  9141.82303656,  5636.53800803,  5418.88227443,
       11462.66093541,  9027.5354582 ,  5399.35456787, 11491.50934705,
        2707.17240262,  6420.71348525,  4597.53132   ,  6388.83354934,
        8746.99978869,  3855.44278016, 11525.34819328,  4097.6513841 ,
       12036.08450377, 12792.13991689, 11801.93258787,  5049.14756639,
        9690.88641262,  1594.81348525, 12222.3972459 ,  8282.75966049,
        2175.02844967,  9917.94182574, 12546.09246672,  9600.23067902,
        9000.48800803, 10527.27685426, 13687.5714482 ,  5311.30711771,
        8626.1752659 ,  4888.61825738,  9646.99851377,  9309.22271607,
       12778.98036557,  2166.35711771,  8871.4153941 ,  1621.05361344,
        7020.64883426, 10192.10934   ,  7996.23991689,  5863.05775164,
        8007.51953229, 10482.58163344, 11254.40488131,  2965.57208213,
        1970.10902656, 11249.30074311, 10128.61476016, 10973.25329295,
        5902.45743115, 13695.0911918 , 12608.97240262,  3283.09182574,
        1661.26061492, 11235.41284426,  7026.28864197,  3973.96412623,
       10422.30998098,  1626.69342115,  1937.42176869,  7555.82431148,
        2691.40456787,  1628.57335705, 10722.18195393,  9912.83896246,
        4520.76348525, 13093.27590689, 12647.2994682 , 10409.15042967,
        5190.56156934,  3967.94023738,  1941.26061492,  5652.11443967,
        5100.63418328,  1421.77399803,  4269.88354934,  4549.69087131,
        8602.88768754,  2968.18036557,  4524.52335705,  4234.58800803,
        4557.21061492,  7243.21602803, 13278.13195393,  1385.21316475,
       11000.83768754,  7191.00106361, 11769.43673312,  3771.88354934,
        6157.09723885, 13336.71507361,  2442.40456787,  2495.15647672,
       13700.73099951, 10197.13450377, 10127.54214623,  4071.7555223 ,
        6496.75297246,  9607.40615623,  3234.82813623,  2986.97972459,
        6943.88099951,  6174.13036557,  4795.65934705,  5096.87431148,
       11283.25329295, 13856.85106361, 11798.90106361,  5819.51411918,
        4806.93896246,  9628.19915475,  3753.50743115, 10436.19787984,
        6460.30584279,  1353.25425443,  9622.36666902, 13169.3153941 ,
        4859.69087131,  2766.29246672,  7763.35201803,  2990.73959639,
        6929.99310066,  5702.4494682 , 13123.89182574,  7027.44023033,
        6437.01826443,  7798.45615623,  9441.88641262,  3318.38736705,
       12098.96443967, 13630.33132   , 12056.14915475, 12114.00392689,
        7474.56825738,  3253.62749525,  1377.69342115,  9075.91157639,
       12361.85233853,  2432.81348525,  5433.92176164,  8004.83227443,
        9692.76634852,  3194.70010918,  6963.40870607, 11282.52494541,
        6777.28864197,  2867.58928295,  8056.43259492,  8114.28736705,
        8790.88768754, 10957.4854582 ,  2685.03641262,  8346.36794393,
        2518.44405508,  7772.75169754,  5110.22654082, 14151.08322885,
        4062.35584279,  3531.66858492,  1440.57335705,  1392.73290836,
        8820.54342115,  1427.41380574,  4247.74755934,  4100.68290836,
        9342.98258787, 10445.06188984, 13325.4354582 , 13669.19533   ,
        7763.35201803, 11758.15711771,  5587.5472459 ,  9602.11061492])

In [109]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,Y_Pred)

In [110]:
r_score

-0.08705343840598312

In [111]:
from sklearn.svm import SVR
regressor_rbf=SVR(kernel="rbf")  
regressor_rbf.fit(X_train, Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [112]:
Y_Pred_rbf=regressor_rbf.predict(X_test)
Y_Pred_rbf

array([9472.81990341, 9438.56295222, 9448.28540499, 9519.10671867,
       9456.8843067 , 9346.46571762, 9278.38895856, 9467.67064596,
       9374.42789755, 9329.83066536, 9347.29964795, 9457.54636079,
       9409.74497911, 9339.94407155, 9307.88581791, 9458.70422382,
       9511.33562714, 9304.62262099, 9373.91448179, 9283.1777493 ,
       9462.79119601, 9497.26123068, 9472.75034196, 9437.69305423,
       9290.23680043, 9339.79442933, 9317.05382571, 9389.9909712 ,
       9328.17842499, 9424.73260313, 9387.76099118, 9508.94006644,
       9523.36476336, 9491.43832846, 9298.42514967, 9322.67614667,
       9434.46457196, 9317.51383869, 9389.66541493, 9284.58054525,
       9359.2686978 , 9317.35471398, 9380.05219075, 9507.32024267,
       9283.42991049, 9286.64157647, 9458.12419693, 9401.22072965,
       9323.78857521, 9496.34364264, 9294.34881061, 9280.56255761,
       9445.28342933, 9467.81939043, 9504.36552318, 9316.28629087,
       9307.00791169, 9457.48195109, 9408.14228782, 9511.41728192,
       9280.175113  , 9523.84297984, 9516.44441131, 9460.50860188,
       9447.58297952, 9467.47142124, 9280.84280026, 9331.98388525,
       9288.115427  , 9388.6953867 , 9519.00691909, 9500.05088212,
       9282.77167723, 9527.25244413, 9511.33967974, 9514.15641039,
       9427.58796637, 9417.49416085, 9366.01731913, 9520.31453618,
       9495.35865208, 9416.10817756, 9289.53767839, 9424.70337511,
       9412.13838406, 9346.4781885 , 9316.10952501, 9304.07109443,
       9509.79813344, 9326.92863586, 9340.04592084, 9490.36717332,
       9310.53278104, 9423.32574097, 9349.56350393, 9335.40581587,
       9490.98727765, 9417.71305822, 9330.17531215, 9495.45868494,
       9292.84240273, 9362.02678322, 9314.7459238 , 9362.86871181,
       9402.37879219, 9309.30735703, 9489.96972602, 9315.41074698,
       9507.46483638, 9516.589022  , 9477.81935948, 9337.57659272,
       9445.08762715, 9279.24145419, 9499.10222781, 9401.26506344,
       9284.66525203, 9457.48195109, 9511.47811459, 9429.40390015,
       9412.62446431, 9462.84221619, 9528.32852824, 9328.8454247 ,
       9416.09050583, 9319.38018334, 9437.19076156, 9420.93125396,
       9514.60808257, 9290.15079078, 9417.04439879, 9280.20610376,
       9374.25701406, 9460.85142357, 9403.110216  , 9347.60629295,
       9400.62812365, 9455.34230112, 9473.34764507, 9291.31417984,
       9283.31446752, 9489.14559607, 9454.72259413, 9485.71118808,
       9346.13353416, 9530.73753234, 9511.85304445, 9292.62095815,
       9283.37719186, 9481.9010833 , 9373.13690586, 9320.61519152,
       9467.10954738, 9278.53339203, 9289.25379993, 9388.02844958,
       9288.9506355 , 9278.26944834, 9458.70422382, 9440.17754413,
       9309.49750086, 9522.02373591, 9512.39112953, 9467.47149913,
       9335.09576022, 9297.88531802, 9283.62818915, 9329.36706304,
       9328.18112775, 9287.300358  , 9309.94128297, 9312.37725395,
       9410.22653164, 9298.90200583, 9308.48993957, 9301.79352375,
       9313.43573004, 9378.78251426, 9511.00784857, 9278.40031266,
       9473.21037431, 9367.50765543, 9502.49987101, 9309.84082326,
       9346.35832347, 9521.36904963, 9288.9715202 , 9285.2244014 ,
       9531.07523885, 9454.05745279, 9460.2739884 , 9303.38867691,
       9359.06205613, 9442.8285014 , 9302.80442091, 9295.20620384,
       9366.98142832, 9345.11151695, 9323.39976724, 9328.45091032,
       9485.78920702, 9531.18876458, 9491.55743486, 9328.7402375 ,
       9318.64209481, 9441.17435335, 9299.45963519, 9473.87570892,
       9356.77687789, 9294.4500472 , 9446.84561429, 9524.21838838,
       9312.587846  , 9293.52643718, 9394.81995893, 9296.01365856,
       9359.67783614, 9340.22319105, 9509.60486928, 9366.04043049,
       9353.0005861 , 9379.2363647 , 9445.03041337, 9299.78754225,
       9507.45594169, 9529.80305687, 9496.88172968, 9503.28818756,
       9372.23317473, 9299.05320039, 9278.5612508 , 9434.605289  ,
       9512.01775617, 9279.77483858, 9334.14670336, 9396.62107587,
       9444.54362096, 9296.17499508, 9373.47544027, 9474.1590345 ,
       9373.11409356, 9287.04198641, 9399.03573372, 9407.94404798,
       9410.26756916, 9479.4614454 , 9285.63502716, 9411.91295818,
       9289.35634189, 9393.02075017, 9323.10839125, 9528.04115114,
       9306.19483737, 9312.14465331, 9278.28576938, 9280.60479632,
       9425.93511862, 9283.16764739, 9299.58559947, 9308.23329622,
       9419.64340713, 9458.35945572, 9524.5096851 , 9523.93167171,
       9394.81995893, 9500.42867664, 9331.30111396, 9428.83733015])

In [113]:
from sklearn.metrics import r2_score
r_score_rbf=r2_score(Y_test,Y_Pred_rbf)
r_score_rbf

-0.10353063408199814

In [ ]:
# Penalty parameter

In [140]:
from sklearn.svm import SVR
regressor_rbf=SVR(kernel="rbf", C=10)  
regressor_rbf.fit(X_train, Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=10)

In [141]:
Y_Pred_rbf=regressor_rbf.predict(X_test)
#Y_Pred_rbf

In [142]:
from sklearn.metrics import r2_score
r_score_rbf=r2_score(Y_test,Y_Pred_rbf)
r_score_rbf

-0.04248495679947917

In [114]:
from sklearn.svm import SVR
regressor_poly=SVR(kernel="poly")  
regressor_poly.fit(X_train, Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(kernel='poly')

In [115]:
Y_Pred_poly=regressor_poly.predict(X_test)
Y_Pred_poly

array([ 9660.9209745 ,  9098.26450111,  9659.09452157, 11323.78259697,
        9047.51336972,  7943.05091868,  7444.10826835,  9826.81722559,
        8395.12136903,  7991.21613364,  7906.10494691,  9274.80078876,
        8742.96360009,  7952.39841317,  7749.77946021,  9359.81094164,
       10338.77968472,  7769.45275939,  8367.23776676,  7531.74772721,
        9294.57283237, 10302.19456598,  9658.18485297,  9022.05181844,
        7628.0117866 ,  8173.02764308,  7628.21245369,  8630.25643145,
        7874.20712333,  8952.25983102,  8481.76188944, 11200.30625268,
       11420.64172112, 10378.42623269,  7541.29680797,  7863.47459672,
        9354.55264925,  7929.56651945,  8599.32466869,  7561.83107673,
        8003.59843677,  7818.36007094,  8352.98551596, 10749.69415013,
        7531.33377041,  7583.939794  ,  9318.02432241,  8569.01183599,
        7762.48545387,  9908.27825512,  7676.72533102,  7477.68901368,
        9157.21627397,  9875.39335337, 11039.03752469,  7910.01385561,
        7815.42634333,  9271.64092455,  8620.72802315, 10341.23716104,
        7485.22314641, 10983.93173226, 10866.56301419,  9529.85947268,
        9446.22382167,  9965.1525475 ,  7503.73246056,  8052.61055545,
        7472.91516353,  8541.93616575, 10705.04547744, 10113.3992314 ,
        7502.62436162, 11517.6951817 , 10338.00743057, 10506.49538446,
        8755.89072891,  8863.61422614,  8199.22996906, 11200.61063549,
       10036.42909183,  9354.58893704,  7616.06486358,  8950.58424913,
        8913.42108752,  8027.87994668,  7933.09081337,  7753.52396482,
       10373.92051308,  8014.61120561,  8175.01432271,  9964.20307673,
        7865.2035158 ,  8845.8903981 ,  8227.40991184,  8042.91386467,
       10015.64631601,  8864.59408222,  8009.89415501, 10683.59317338,
        7651.17741883,  8334.89954747,  7876.39880924,  8360.36242104,
        8634.55814868,  7648.17419673,  9740.06657517,  7892.07310189,
       10627.34363613, 10800.08357804,  9477.34334642,  8205.0301941 ,
        9155.61741138,  7486.06226972, 10951.99049414,  8570.42506309,
        7457.67212403,  9271.64092455, 10952.71734956,  8864.47985634,
        8951.72653906,  9141.71546334, 11894.1017761 ,  8057.20503267,
        8759.64509307,  7708.08883599,  8986.6023208 ,  8678.52276852,
       11229.80319613,  7628.58001458,  8828.77217105,  7503.86652768,
        8392.52703505,  9207.43312467,  8693.36723035,  8135.33742369,
        8508.15318642,  9153.41748346,  9412.78638222,  7590.91784297,
        7541.24453549,  9865.40351097,  9638.76396897,  9990.75905985,
        8026.26102362, 11616.79564757, 10891.70793381,  7546.1312092 ,
        7426.92885097,  9656.20765357,  8312.70624868,  7986.04500295,
        9638.85570496,  7477.55605142,  7593.48022222,  8508.01309812,
        7604.92932881,  7469.09530356,  9359.81094164,  9257.88921278,
        7814.54677053, 11553.09071122, 10393.65076206,  9965.82235948,
        7829.95111834,  7704.80561016,  7427.08868109,  7971.25218013,
        7893.64691697,  7559.92529659,  7830.02601263,  7760.95865213,
        8777.56980884,  7729.7215515 ,  7782.58662244,  7744.97193988,
        7700.17604996,  8223.03066524, 10492.13953048,  7444.21761562,
        9708.40667014,  8327.12410205, 10487.57276946,  7828.33062468,
        7965.050041  , 10731.9845945 ,  7604.30712838,  7520.14565743,
       11414.6277077 ,  9464.07173156,  9483.54690682,  7725.19403799,
        8138.51873885,  9002.22783839,  7771.49026365,  7598.8119939 ,
        8300.0650315 ,  8214.46240463,  8000.88797991,  7931.08390644,
        9992.35651216, 11484.14215839, 10119.97326176,  7877.6266517 ,
        7889.35795568,  9376.5303272 ,  7620.63457728,  9845.39521369,
        8319.33418963,  7600.95153348,  9316.00972502, 11035.29179059,
        7761.51174519,  7663.76486485,  8553.67623077,  7575.11142849,
        8188.26047668,  7914.19728119, 10378.1202705 ,  8014.9940923 ,
        8328.33605809,  8276.23033054,  9153.82032257,  7606.67897327,
       10569.6269014 , 11755.30630947, 10519.8380372 , 10132.31536852,
        8164.48236592,  7632.1365482 ,  7477.08124126,  9393.18753375,
       10829.31520748,  7487.52273868,  7885.3116963 ,  8678.02051477,
        9116.69888074,  7675.3729662 ,  8339.35198802,  9457.52252635,
        8311.47768769,  7585.56705623,  8839.20551991,  8613.06467067,
        8779.5965355 ,  9823.43975046,  7510.88757157,  8911.90077694,
        7516.92191288,  8408.09634695,  7882.79788774, 11261.81431086,
        7801.04523722,  7882.5301533 ,  7468.5176125 ,  7413.8307889 ,
        9059.89782774,  7530.88252289,  7647.72842319,  7676.51313417,
        8614.36851877,  9315.32691955, 11100.53899667, 10978.683876  ,
        8553.67623077, 10829.52176535,  8098.98013   ,  8829.41893529])

In [116]:
from sklearn.metrics import r2_score
r_score_poly=r2_score(Y_test,Y_Pred_poly)
r_score_poly

-0.0729269969753068

In [117]:
from sklearn.svm import SVR
regressor_sig=SVR(kernel="sigmoid")  
regressor_sig.fit(X_train, Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(kernel='sigmoid')

In [118]:
Y_Pred_sig=regressor_sig.predict(X_test)
Y_Pred_sig

array([9441.54548783, 9445.39269785, 9436.29603231, 9431.76728409,
       9453.9807273 , 9461.86097529, 9456.16490064, 9437.5387542 ,
       9449.5835746 , 9451.70993209, 9464.34747324, 9446.27265059,
       9447.79574617, 9458.68235393, 9456.01227899, 9444.41540223,
       9441.68250455, 9452.00320649, 9450.60061226, 9453.52086135,
       9447.54368834, 9437.10343887, 9441.5799215 , 9447.31917074,
       9451.14296955, 9445.75546965, 9468.87518715, 9445.68573775,
       9458.29645698, 9445.63425066, 9450.50070444, 9431.01020233,
       9431.88675357, 9434.98784589, 9465.01400742, 9456.36637018,
       9438.59392286, 9447.90559591, 9446.65158271, 9450.78627109,
       9463.41357551, 9456.63062215, 9453.29839797, 9434.1981959 ,
       9447.70133959, 9451.87127972, 9445.31926639, 9451.42267118,
       9463.37483879, 9444.46913529, 9450.31653564, 9455.77163795,
       9445.70760458, 9436.87087438, 9431.41608746, 9448.80219328,
       9449.19175036, 9446.30505778, 9451.74623649, 9441.66174763,
       9454.8946281 , 9436.04935818, 9435.08130527, 9441.05154462,
       9439.76184609, 9435.57405242, 9453.14335028, 9448.82034722,
       9462.75486897, 9448.45780875, 9438.01186453, 9441.03473554,
       9456.34167925, 9432.01542687, 9441.69618008, 9439.31353934,
       9453.14176919, 9446.22024387, 9455.5427864 , 9432.86641784,
       9440.85724008, 9434.7105342 , 9452.06318992, 9445.65768154,
       9443.28544767, 9457.03244451, 9443.25681926, 9453.01276732,
       9439.85820537, 9448.28784504, 9445.72566673, 9440.63138766,
       9444.21752616, 9448.50673153, 9447.69675377, 9451.41095116,
       9439.87050045, 9446.24726531, 9450.75349909, 9432.76853751,
       9452.1529861 , 9447.71314478, 9450.65660629, 9446.84027301,
       9449.33941335, 9463.94106738, 9446.07973476, 9449.7510395 ,
       9435.46144925, 9435.78908507, 9448.40560635, 9440.75913356,
       9445.69762127, 9451.80792053, 9431.28525715, 9451.39570909,
       9461.19495747, 9446.30505778, 9433.16026613, 9449.84098148,
       9442.41026955, 9453.20093057, 9430.07571525, 9446.38198855,
       9449.15918801, 9464.83321039, 9448.27188041, 9453.82063684,
       9431.66014347, 9448.38151201, 9447.17588371, 9450.0467978 ,
       9449.63452188, 9449.58467304, 9447.45631626, 9451.64398833,
       9453.65638045, 9449.22223259, 9448.18586381, 9457.06364792,
       9452.56739079, 9442.26144383, 9437.83679782, 9438.8944304 ,
       9457.01891167, 9432.13469493, 9433.75336485, 9461.3014708 ,
       9461.56764666, 9444.61078128, 9452.73973343, 9443.10565789,
       9440.5164103 , 9452.5878102 , 9445.58453211, 9449.53817879,
       9452.97739274, 9453.45772567, 9444.41540223, 9441.89888995,
       9451.79708434, 9430.84331301, 9440.87850394, 9435.56297319,
       9464.00763549, 9451.13420992, 9461.65776611, 9452.74866971,
       9457.10808812, 9445.33410134, 9450.85124686, 9457.91237788,
       9446.81795252, 9449.38729536, 9453.79924959, 9451.07902973,
       9462.54180775, 9459.03525916, 9438.33499292, 9456.14928083,
       9440.73688548, 9450.08693363, 9435.95082455, 9450.89934868,
       9460.55744235, 9438.92938597, 9452.99998501, 9457.62735754,
       9433.8536464 , 9440.82456982, 9441.92262665, 9455.01051086,
       9456.04310471, 9449.63603373, 9449.31594687, 9459.31472803,
       9451.1296029 , 9446.23003073, 9446.69638661, 9454.89839971,
       9438.88810073, 9433.2665371 , 9438.33308186, 9458.23794455,
       9452.36013729, 9439.61605628, 9460.42383049, 9438.49161084,
       9446.31952389, 9442.42325628, 9442.19142109, 9435.43910952,
       9457.90360211, 9451.23406767, 9449.95340309, 9461.51264311,
       9453.73802437, 9461.06107789, 9439.83227497, 9465.43294247,
       9444.1073305 , 9456.59151533, 9445.72121934, 9461.62265959,
       9436.12498658, 9431.06458962, 9434.5043867 , 9442.10540644,
       9459.59002863, 9459.36811304, 9452.6071269 , 9437.9037599 ,
       9434.36991463, 9451.68642166, 9460.25544439, 9446.06936763,
       9446.63312292, 9453.18877267, 9451.66128077, 9447.14718142,
       9452.76712326, 9449.03847017, 9441.80637584, 9451.9001394 ,
       9446.77813873, 9440.18202129, 9458.5926322 , 9443.27497253,
       9461.07868427, 9455.37351902, 9455.2914943 , 9434.30769101,
       9450.08633192, 9443.41053214, 9453.49237304, 9459.8349411 ,
       9443.0246981 , 9447.64882175, 9458.17375346, 9461.53783164,
       9456.0760472 , 9445.39046377, 9434.80689937, 9436.06157298,
       9449.95340309, 9432.34861905, 9444.71555322, 9450.88485499])

In [119]:
from sklearn.metrics import r2_score
r_score_sig=r2_score(Y_test,Y_Pred_sig)
r_score_sig

-0.1061359604346106

In [120]:
#Standardization

In [121]:
X_train

      age  bmi  children  sex_male  smoker_yes
621    37   34         4         1           1
194    18   34         0         1           0
240    23   36         2         0           1
1168   32   35         2         1           0
1192   58   32         1         0           0
...   ...  ...       ...       ...         ...
763    27   26         0         1           0
835    42   35         2         1           0
1216   40   25         0         1           0
559    19   35         0         1           0
684    33   18         1         0           0

[1070 rows x 5 columns]

In [122]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [124]:
X_train # Values are changed to defined range from -1 to 1 as standardized value

array([[-0.14853305,  0.60616004,  2.41394802,  1.01506676,  1.97125461],
       [-1.49780784,  0.60616004, -0.89219519,  1.01506676, -0.50729114],
       [-1.14273553,  0.92836135,  0.76087642, -0.98515688,  1.97125461],
       ...,
       [ 0.06451033, -0.84374587, -0.89219519,  1.01506676, -0.50729114],
       [-1.42679338,  0.7672607 , -0.89219519,  1.01506676, -0.50729114],
       [-0.4325909 , -1.97145047, -0.06565939, -0.98515688, -0.50729114]],
      shape=(1070, 5))

In [ ]:
# Creating model after standardization

In [125]:
from sklearn.svm import SVR
regressor_std=SVR(kernel="linear")  
regressor_std.fit(X_train, Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(kernel='linear')

In [126]:
Y_Pred_std=regressor_std.predict(X_test)
Y_Pred_std

array([ 9497.38261822,  9299.60606954, 10835.9267438 ,  9883.66024203,
        9295.78495225,  8687.51673118,  8139.89476556,  9598.98043136,
        9046.29978619,  8792.81330382,  8778.88944638,  9417.76844472,
        9149.18505919,  8682.7027672 ,  9844.08612006,  9476.29203007,
        9697.15947922,  8540.91683811,  8997.52648658,  9602.12013912,
       10778.57620416,  9717.84771536,  9461.01492789, 10586.44088607,
        8363.87842318,  8819.72532158,  8420.22874915,  9153.41647213,
        8618.12765561,  9271.39864828,  9100.23950419, 11222.96711768,
        9910.63010103,  9647.39333292,  9647.07232144,  8601.7931902 ,
        9394.08704957, 10004.02731952, 10450.88668225,  8289.55302585,
        8742.34155703,  8563.30282976, 10274.07836393, 11169.43769533,
        9591.60710332,  8391.0284812 ,  9465.65663648,  9078.78851799,
        8575.23362685,  9611.84623389,  8413.0041772 ,  8299.89380626,
       10671.04922257, 10954.97422682,  9803.63577288,  8610.78072588,
        8535.5702207 ,  9342.37774052,  9254.76956969,  9734.41227739,
        8197.88569747, 11293.29914233,  9904.63641603,  9480.69569839,
        9511.89697033,  9556.38101577,  9564.51488653, 10170.07788646,
        8274.03915174,  9157.87798169,  9778.19141401,  9653.50270039,
        9570.21395835,  9938.48506788,  9698.04458707,  9729.95076783,
        9149.41515582,  9233.79339569, 10226.37037119, 11245.00065491,
        9590.16515107, 10638.09235389,  8353.24302959,  9234.1458501 ,
       10546.83532116, 10149.92230376,  8648.15588184,  8493.02864635,
        9728.71320557, 10031.34963293,  8895.11602578,  9562.31018422,
        8562.66243749,  9240.37757537,  8825.77684782,  8756.7980679 ,
       10918.30397969, 10579.15179757,  8767.08100708,  9716.90476627,
        8390.84828218,  8927.60475758,  8664.9006429 , 10246.34575487,
       10519.9233034 ,  8425.16507091,  9525.46768169,  8601.03044014,
        9728.30290992, 11127.6010298 ,  9552.2652853 ,  8856.21536969,
        9326.57592854,  9537.54502753, 11158.39200609,  9116.04131617,
        8208.93138671,  9342.37774052,  9835.06714145,  9293.0797311 ,
       10631.9763111 ,  9333.39020484, 10007.99650123,  8819.02041275,
        9165.5195246 ,  8564.24577885, 10613.05829066, 10531.67390146,
       11202.04878491,  8358.17935135,  9224.04310995,  8250.710211  ,
        8971.79418984,  9337.44141875, 10429.43569605, 10128.59367534,
       10365.62333452,  9385.86226395, 10796.14823183,  8374.92411241,
        8268.28223868,  9541.03939704,  9496.26741374,  9556.61111239,
        8767.3111037 ,  9965.45492688,  9825.31685571,  8370.52044409,
        8123.43794236,  9519.41615545,  8939.88800908,  9992.98163028,
        9481.04815281,  8218.80403024,  8353.01293296,  9036.36930143,
        8379.86043418,  8208.16863665,  9476.29203007,  9416.65324024,
        8653.02768705,  9931.90088821,  9708.67998066,  9555.49590792,
        8602.55594026,  8588.10012105,  9469.68145209,  8783.06301808,
        8665.13073953,  8278.1548822 ,  8626.41028246,  8589.56777994,
        9197.07325095,  8460.35971553,  8631.75689988,  8625.70537364,
        8547.02620559,  8912.79579229, 11169.84799097,  8139.00965771,
        9546.15591783,  9007.80942575,  9690.69765733,  8551.90468611,
        8772.65772111, 11138.99917345,  8342.607636  ,  8289.9633215 ,
        9933.54874612,  9454.61094724, 10740.91311034,  8547.14856338,
        8843.40671673, 10591.25485005,  8497.96496811,  8354.00577965,
        8959.92123399,  8922.08588478,  8744.16236199,  8686.4015267 ,
        9594.74901842, 11288.65743374,  9669.60706918, 10074.35934417,
        8680.35000046, 10719.41222654,  8455.481235  ,  9502.67139439,
        8949.40819819,  8319.8113487 ,  9368.23239504,  9847.70284736,
        8627.70568596,  8402.36878361,  9062.45405258,  8332.73499247,
        8938.2979924 ,  8698.6847782 ,  9804.10390977,  8833.18161879,
        8980.96192454,  9009.45728366,  9289.32313037,  8371.22535291,
        9718.55262418,  9985.84060621,  9760.38928971,  9633.46947548,
        8949.69613605,  8391.61103224,  8181.55123206,  9367.46964498,
        9777.42866394,  8342.0829262 ,  8671.7149192 ,  9142.2484251 ,
        9315.94053495,  9763.17654306,  8949.63829482,  9498.67802172,
        8902.6352109 ,  9767.05550158,  9196.31050089,  9069.39068667,
        9233.44094128,  9545.62326439,  8315.69561824,  9202.36202713,
        8258.40959515,  9009.27708464,  9995.03978384, 11315.80749176,
        8600.32553131,  8610.55062925,  8171.80094632,  8096.46808336,
        9266.05203087,  8246.24870144,  8551.25761853,  8483.68865626,
        9202.29751058, 10736.50944201, 11202.81153497,  9911.57305012,
        9062.45405258,  9754.51001886, 10186.53470966,  9282.44433752])

In [127]:
from sklearn.metrics import r2_score
r_score_std=r2_score(Y_test,Y_Pred_std)
r_score_std

-0.012166509835097594

In [ ]:
# Penalty parameter