In [84]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")

In [85]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [86]:
dataset=pd.get_dummies(dataset, drop_first=True)
dataset=dataset.astype(int)
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [87]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [88]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [89]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [122]:
from sklearn.ensemble import AdaBoostRegressor
regressor=AdaBoostRegressor(estimator=None, n_estimators=2)
regressor=regressor.fit(X_train, Y_train)
regressor

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

AdaBoostRegressor(n_estimators=2)

In [123]:
Y_pred=regressor.predict(X_test)

In [124]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test, Y_pred)
r_score

0.8740167817941462

In [125]:
# estimator=None, n_estimators=50, learning_rate=10.0, loss='exponential', random_state=None

In [126]:
#regressor=AdaBoostRegressor(n_estimators=50, learning_rate=10.0, random_state=None)
#regressor=regressor.fit(X_train, Y_train)
#regressor

In [127]:
#r_score=r2_score(Y_test, Y_pred)
#r_score

In [128]:
import pickle
filename="insurance_pre_AdaBoost.sav"
pickle.dump(regressor, open(filename,'wb'))

In [129]:
loaded_model=pickle.load(open("insurance_pre_AdaBoost.sav",'rb'))
result=loaded_model.predict([[52,30,1,1,0]])
result

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but AdaBoostRegressor was fitted with feature names
  warnings.warn(

array([14057.3030303])

In [83]:
X_test, Y_test, Y_pred

(      age  bmi  children  sex_male  smoker_yes
 578    52   30         1         1           0
 610    47   29         1         0           0
 569    48   40         2         1           1
 1034   61   38         0         1           0
 198    51   18         0         0           0
 ...   ...  ...       ...       ...         ...
 1261   28   37         1         1           0
 494    21   25         4         1           1
 97     55   38         0         1           0
 418    64   39         1         1           0
 920    62   25         0         0           0

 [402 rows x 5 columns],
       charges
 578      9724
 610      8547
 569     45702
 1034    12950
 198      9644
 ...       ...
 1261     3277
 494     17942
 97      10226
 418     14418
 920     13451

 [402 rows x 1 columns],
 array([14622.03370787, 11483.01369863, 46400.79411765, 14178.41721854,
        14178.41721854,  6763.7559322 ,  5494.44736842, 14622.03370787,
         7187.45454545,  7187.45454545,  6763.7559322 , 14622.03370787,
        10430.33333333,  6763.7559322 , 19426.96      , 14622.03370787,
        14178.41721854,  7187.45454545,  7187.45454545, 37672.42592593,
        25719.52083333, 14622.03370787, 14178.41721854, 25719.52083333,
         9598.43706294, 10042.04878049,  6763.7559322 , 10042.04878049,
         6763.7559322 , 11483.01369863,  6763.7559322 , 46400.79411765,
        14178.41721854, 14178.41721854, 19426.96      ,  6763.7559322 ,
        11483.01369863, 37672.42592593, 42263.68085106,  9598.43706294,
         6763.7559322 ,  6763.7559322 , 19426.96      , 46400.79411765,
        37672.42592593,  7187.45454545, 14622.03370787,  6763.7559322 ,
         6763.7559322 , 14622.03370787,  9598.43706294,  5494.44736842,
        25719.52083333, 46400.79411765, 14178.41721854,  9598.43706294,
         9598.43706294, 14178.41721854, 10207.60810811, 16097.58333333,
         5494.44736842, 46400.79411765, 19523.39622642, 14622.03370787,
        11483.01369863, 14622.03370787, 37672.42592593, 42263.68085106,
         6325.80985915,  7187.45454545, 14178.41721854, 14622.03370787,
        18100.79310345, 14178.41721854, 14178.41721854, 14178.41721854,
        11483.01369863, 11483.01369863, 19426.96      , 46400.79411765,
        14178.41721854, 46400.79411765,  7187.45454545, 11483.01369863,
        46400.79411765, 19426.96      , 10042.04878049,  7187.45454545,
        16097.58333333, 37672.42592593, 10042.04878049, 14178.41721854,
         9598.43706294, 11483.01369863,  9598.43706294,  7187.45454545,
        46400.79411765, 46400.79411765,  7187.45454545, 14178.41721854,
         7187.45454545, 10042.04878049, 10042.04878049, 42263.68085106,
        25719.52083333,  6763.7559322 , 14178.41721854,  9598.43706294,
        14178.41721854, 46400.79411765, 14622.03370787, 10042.04878049,
        11483.01369863, 37672.42592593, 46400.79411765,  6763.7559322 ,
         6325.80985915, 14178.41721854, 16097.58333333, 11483.01369863,
        46400.79411765, 14178.41721854, 14178.41721854, 10042.04878049,
        11483.01369863,  6763.7559322 , 25719.52083333, 25719.52083333,
        46400.79411765,  9598.43706294, 11483.01369863,  5494.44736842,
         7187.45454545, 14178.41721854, 46400.79411765, 42263.68085106,
        25719.52083333, 14622.03370787, 25719.52083333,  6763.7559322 ,
         7187.45454545, 14178.41721854, 11483.01369863, 14178.41721854,
         6763.7559322 , 14178.41721854, 16097.58333333,  6763.7559322 ,
         5494.44736842, 14622.03370787,  6763.7559322 , 37672.42592593,
        14622.03370787,  5494.44736842,  5494.44736842,  7187.45454545,
         7187.45454545,  5494.44736842, 14622.03370787, 11483.01369863,
         7187.45454545, 14178.41721854, 14178.41721854, 14622.03370787,
         6763.7559322 , 10042.04878049, 18100.79310345,  7187.45454545,
         6763.7559322 ,  5494.44736842, 10042.04878049,  6763.7559322 ,
        10430.33333333,  9598.43706294,  7187.45454545, 10042.04878049,
         6763.7559322 ,  6763.7559322 , 25719.52083333,  5494.44736842,
        14622.03370787,  7187.45454545, 14178.41721854,  9598.43706294,
         6763.7559322 , 25719.52083333,  7187.45454545,  6325.80985915,
        14178.41721854, 11483.01369863, 46400.79411765,  7187.45454545,
         6763.7559322 , 25719.52083333,  9598.43706294,  6763.7559322 ,
         7187.45454545, 10042.04878049, 10042.04878049,  6763.7559322 ,
        14622.03370787, 46400.79411765, 14622.03370787, 19426.96      ,
         7187.45454545, 46400.79411765,  6763.7559322 , 14178.41721854,
        10042.04878049,  5494.44736842, 11483.01369863, 14178.41721854,
         6763.7559322 ,  9598.43706294,  6763.7559322 ,  6763.7559322 ,
         6763.7559322 ,  6763.7559322 , 19523.39622642,  6763.7559322 ,
        10042.04878049,  6763.7559322 , 11483.01369863,  6763.7559322 ,
        14178.41721854, 14178.41721854, 14622.03370787, 14178.41721854,
         6763.7559322 ,  6763.7559322 ,  5494.44736842, 11483.01369863,
        14178.41721854,  5494.44736842,  6763.7559322 ,  7187.45454545,
        11483.01369863, 37672.42592593,  6763.7559322 , 14622.03370787,
         6763.7559322 , 37672.42592593, 10042.04878049, 10207.60810811,
        10430.33333333, 14622.03370787,  6325.80985915, 10430.33333333,
         6325.80985915,  6763.7559322 , 19426.96      , 46400.79411765,
        10042.04878049, 10042.04878049,  5494.44736842,  5494.44736842,
        11483.01369863,  5494.44736842,  6763.7559322 ,  6763.7559322 ,
        11483.01369863, 25719.52083333, 46400.79411765, 19523.39622642,
         6763.7559322 , 14178.41721854, 37672.42592593, 11483.01369863,
        42263.68085106,  5494.44736842, 37672.42592593, 10042.04878049,
        14622.03370787,  6763.7559322 , 42263.68085106, 10042.04878049,
        14178.41721854, 11483.01369863,  7187.45454545, 16097.58333333,
        14178.41721854,  9598.43706294, 14178.41721854,  5494.44736842,
        10042.04878049,  7187.45454545, 10042.04878049, 25719.52083333,
        10042.04878049,  5494.44736842,  5494.44736842, 46400.79411765,
        11483.01369863,  7187.45454545, 14622.03370787, 14622.03370787,
        37672.42592593,  6763.7559322 ,  7187.45454545, 14178.41721854,
         5494.44736842,  7187.45454545, 19426.96      , 19426.96      ,
        14178.41721854,  6763.7559322 ,  7187.45454545, 11483.01369863,
        14178.41721854, 18100.79310345, 19426.96      , 10042.04878049,
        18100.79310345,  5494.44736842, 10042.04878049,  9598.43706294,
        11483.01369863,  5494.44736842, 10207.60810811, 46400.79411765,
        10042.04878049,  7187.45454545,  5494.44736842, 11483.01369863,
         9598.43706294, 14178.41721854, 46400.79411765, 19426.96      ,
        11483.01369863, 46400.79411765, 14622.03370787,  7187.45454545,
        14622.03370787, 10042.04878049, 25719.52083333,  7187.45454545,
        14178.41721854,  5494.44736842, 18100.79310345,  6763.7559322 ,
        25719.52083333, 10042.04878049,  6763.7559322 , 37672.42592593,
         7187.45454545,  6763.7559322 , 25719.52083333,  5494.44736842,
        10207.60810811,  5494.44736842, 11483.01369863,  6763.7559322 ,
        10042.04878049,  7187.45454545, 46400.79411765, 11483.01369863,
        42263.68085106, 37672.42592593,  6763.7559322 ,  7187.45454545,
         5494.44736842,  6763.7559322 ,  5494.44736842, 11483.01369863,
        46400.79411765, 14178.41721854,  5494.44736842, 14178.41721854,
         9598.43706294, 11483.01369863,  6763.7559322 ,  9598.43706294,
         7187.45454545, 37672.42592593,  6763.7559322 ,  5494.44736842,
        42263.68085106, 14622.03370787, 46400.79411765, 14178.41721854,
        10042.04878049,  6763.7559322 ,  6325.80985915, 14622.03370787,
         6763.7559322 ,  5494.44736842, 14622.03370787,  6763.7559322 ,
         6763.7559322 ,  7187.45454545,  6763.7559322 , 37672.42592593,
         7187.45454545, 14178.41721854,  5494.44736842, 10042.04878049,
        14178.41721854, 10042.04878049, 18100.79310345, 14178.41721854,
        16097.58333333, 14178.41721854]))

In [33]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [130]:
estimator=regressor.estimator_
estimator

DecisionTreeRegressor(max_depth=3)

In [131]:
estimators=regressor.estimators_
estimators

[DecisionTreeRegressor(max_depth=3, random_state=1213879563),
 DecisionTreeRegressor(max_depth=3, random_state=36185339)]

In [132]:
estimator_errors=regressor.estimator_errors_ # Regression error for each estimator in the boosted ensemble.
estimator_errors

array([0.11892565, 0.23478958])

In [133]:
n_features_in=regressor.n_features_in_ # Number of features seen during fit.
n_features_in

5

In [134]:
feature_names_in=regressor.feature_names_in_ # Names of features seen during fit. Defined only when X has feature names that are all strings.
feature_names_in

array(['age', 'bmi', 'children', 'sex_male', 'smoker_yes'], dtype=object)