In [1]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset, drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
dataset=dataset.astype(int)
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [8]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [12]:
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [13]:
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(independent,dependent, test_size=0.20, random_state=0)

In [30]:
from sklearn.ensemble import GradientBoostingRegressor
regressor=GradientBoostingRegressor(loss='absolute_error', learning_rate=0.5, n_estimators=500, min_samples_split=2, min_samples_leaf=10, max_depth=10,random_state=0)
regressor=regressor.fit(X_train, Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:672: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

In [31]:
regressor

GradientBoostingRegressor(learning_rate=0.5, loss='absolute_error',
                          max_depth=10, min_samples_leaf=10, n_estimators=500,
                          random_state=0)

In [32]:
Y_pred=regressor.predict(X_test)
Y_pred

array([ 9562.04261531,  8776.06240351, 47291.30302383, 13341.9330327 ,
        9558.69672045,  4121.59921805,  1615.46795736, 10911.85179114,
        6996.39943313,  5036.32749288,  6625.03714647, 10517.01847116,
        8211.97731402,  3860.55700906, 17744.16184742, 10792.87749436,
       12283.28436236,  3129.80879934,  6280.23072367, 33512.92096246,
       22091.92204145, 12575.06392897,  9607.89320377, 20238.93028194,
        1422.04092333,  4504.69940354,  2853.94599501,  8889.05510209,
        4034.16175566,  8251.11476119,  8076.27456926, 48520.48243945,
       13798.89176547, 10572.43920162, 15598.50186657,  3553.99933593,
        8396.22247529, 37794.96684975, 39467.09041003,  1879.72195254,
        5212.8301895 ,  2866.85191377, 21848.27871961, 39858.30544907,
       36164.4454944 ,  3572.91431104, 11031.49231029,  6752.58493434,
        4761.24289964, 12097.01099215,  2521.32931498,  4197.54353293,
       32716.38299138, 40284.09649647, 11847.45484163,  3056.49514554,
        2392.02891076,  8220.23245928,  9944.12015766, 13115.62152341,
        1131.6750421 , 46430.69164184, 14690.84701059, 11059.03508066,
       10471.99303801,  9524.83705825, 33125.00201179, 37718.09793663,
        4203.4398194 ,  8888.03106401, 13330.24322314, 10970.89522291,
       17514.7561965 , 13901.64214158, 12632.11904862, 12337.27915314,
        7431.81467309,  7945.76263694, 18512.01924511, 47293.22614365,
       11657.3642351 , 46634.76556974,  1656.27086454,  7658.83465262,
       41170.80756311, 18363.13104176,  3398.76343722,  2707.56062867,
       12637.97703038, 36950.06612344,  5706.94293788, 10821.21082765,
        2828.33893479,  9390.49894688,  4083.82300085,  4778.32594249,
       44605.80989756, 32787.9079823 ,  5079.62991673, 10698.14182242,
        2013.10066062,  5304.89698347,  4160.1241682 , 38860.222387  ,
       23902.56253183,  3503.08710333, 10554.0764674 ,  2652.53993045,
       11389.55893642, 46350.82539934, 12227.40596718,  4716.88453121,
        9578.47615532, 33704.54667562, 41450.9148663 ,  7021.67531301,
        1986.44165802,  8220.23245928, 14480.41524403,  8658.82303984,
       43417.14062329,  9935.67783069, 14567.68204583,  5223.34013458,
        8604.86020075,  4825.2433074 , 18176.57678812, 19325.62632671,
       48166.55994745,  1546.08534143,  8845.81547971,  1567.57354132,
        6359.32883497,  9008.30289413, 41767.41149996, 33534.14357916,
       25520.16106412, 10359.69035131, 25933.23628188,  3292.37044143,
        1896.29260993, 10526.31281439,  9013.77913291, 10401.21034212,
        5450.12655728, 14491.86649307, 13973.90612317,  3976.48983761,
        1595.67778541, 10817.97253876,  6301.56373049, 41115.13685731,
        9477.3501247 ,  2109.22460434,  2686.18488347,  7251.88606604,
        2503.33098636,  2494.83306701, 10792.87749436, 10531.57960464,
        4621.36781743, 12864.14215014, 12494.61096454,  8580.85406237,
        3916.21945345,  5469.82797411, 14370.25117544,  5697.06311998,
        4034.34709943,  1795.78949914,  3220.49242759,  3773.92689284,
        8983.99214714,  1892.87201221,  4690.28899851,  5760.79231903,
        4440.64481116,  5699.46666471, 43116.68663653,  1360.44556608,
       11960.74714931,  5820.61212444, 11115.0852228 ,  2763.54710076,
        7147.51094862, 28730.23903358,  1770.21359797,  2596.32884534,
       15127.94154119,  9833.76736305, 40054.53138369,  4573.37269869,
        5872.33813611, 25006.6511515 ,  2213.29091117,  2345.73186991,
        5500.74158643,  5657.04241738,  4030.12692579,  3740.06584294,
       11586.23924913, 49767.53479573, 12657.81151913, 18733.38802654,
        4483.91585715, 43249.05885806,  4215.4415641 ,  9020.75592981,
        6116.88113462,  1142.39555004,  8497.71552529, 13668.88920887,
        4625.96564102,  2685.40811146,  6178.18292652,  2352.26544619,
        6652.10891773,  5381.5491414 , 13998.74361497,  6976.63310067,
        6153.27901392,  7960.00439818,  8236.87763407,  3387.2503706 ,
       12229.47327357, 14561.10161419, 12769.64381589, 12100.77700592,
        7141.22345577,  3219.31164853,  1491.05467455,  7606.11227676,
       12416.84608551,  4477.32393412,  4700.11145368,  6832.28867355,
        9446.43729155, 34623.94686238,  5443.25408323, 10566.13138844,
        5314.00359589, 37552.68700049,  7565.47782337,  5800.7724568 ,
        8036.64971119,  9651.96601469,  3498.52625127,  7219.70221277,
        2563.33784387,  6352.03440163, 21254.02892311, 45587.64872686,
        4598.6950215 ,  3008.95654977,  2164.28502512,  1765.99193308,
        7180.41955622,  1884.12861735,  5023.18998879,  3930.67075632,
        8660.83430435, 17576.39690387, 48585.38989173, 15011.69624647,
        6178.18292652, 11298.84386009, 38402.34877209,  8921.69129384])

In [33]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test, Y_pred)
r_score

0.8826084349313728

In [34]:
from sklearn.ensemble import GradientBoostingRegressor
regressor=GradientBoostingRegressor(random_state=0)
regressor=regressor.fit(X_train, Y_train)
Y_pred=regressor.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(Y_test, Y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:672: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

0.8949453072934336

In [39]:
Pred_Test=regressor.predict([[47,29,1,0,0]])
Pred_Test

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(

array([10556.94759871])

In [40]:
X_test, Y_test, Y_pred

(      age  bmi  children  sex_male  smoker_yes
 578    52   30         1         1           0
 610    47   29         1         0           0
 569    48   40         2         1           1
 1034   61   38         0         1           0
 198    51   18         0         0           0
 ...   ...  ...       ...       ...         ...
 1084   62   30         2         0           0
 726    41   28         1         1           0
 1132   57   40         0         1           0
 725    30   39         3         0           1
 963    46   24         3         1           0

 [268 rows x 5 columns],
       charges
 578      9724
 610      8547
 569     45702
 1034    12950
 198      9644
 ...       ...
 1084    15019
 726      6664
 1132    20709
 725     40932
 963      9500

 [268 rows x 1 columns],
 array([13216.49582896, 10556.94759871, 44803.64266926, 14319.25535989,
        10624.03489153,  5243.99451563,  2064.38790978, 12870.0510957 ,
         7377.13170757,  6561.23323922,  6120.83900401, 13489.59675674,
         9439.73982679,  5771.06316165, 19508.83088801, 12754.18647768,
        14058.63269692,  5113.36550149,  7361.44528947, 35350.15881187,
        24233.2777698 , 14070.36785881, 12268.13786884, 26817.21470378,
         3141.93141423,  6758.63717494,  5204.73124585,  7973.81831495,
         4179.29677624, 10688.72392043,  7796.09747746, 52326.98991756,
        14808.18563894, 12180.93283199, 18345.55812591,  5043.16184217,
        10389.12753652, 37586.69467423, 38944.10013675,  3217.87843872,
         4901.9617242 ,  5543.27680425, 21159.1032262 , 46256.13010321,
        36868.65136591,  5693.53988859, 13513.06654431,  7262.75519365,
         5347.99902669, 11989.2814972 ,  3524.60755409,  6235.74077526,
        26231.39463104, 45112.38503511, 11055.49060371,  4564.24748752,
         3652.25045058, 11714.30973808,  9506.97257526, 15893.71972107,
         2864.02091592, 45742.73203365, 17024.06598749, 12960.59240943,
        13135.05564486, 10414.7583872 , 35025.95441791, 39596.16385441,
         4974.07288876,  9110.27907689, 14469.98059888, 13057.24692851,
        18849.16606637, 14692.61828329, 14667.67699217, 14113.50705822,
         8959.50246853, 10010.20281023, 18934.4409861 , 48179.81313387,
        11598.59031679, 48834.7766989 ,  3141.93141423, 10451.16129252,
        41136.59293141, 18783.01834687,  4971.91139361,  3891.69645133,
        14493.81576846, 38704.98013508,  7593.80426263, 12217.24213335,
         3665.41605925, 11370.1727859 ,  5443.2578011 ,  6076.97927636,
        44149.37159498, 41561.8707038 ,  6868.0052155 , 11012.13715221,
         3635.47275912,  6410.40221731,  7241.4429266 , 39812.1053779 ,
        24952.73230141,  4711.53765318, 11285.56836153,  4803.50177618,
        11972.76024999, 44898.32851008, 13305.79955299,  5597.81119561,
        11001.64946114, 34480.34534286, 49348.42603087,  7671.53070909,
         3224.87078922, 11714.30973808, 18211.32717499,  9276.48070285,
        42343.85162558, 12800.46913732, 13517.85313647,  7439.85067108,
        10202.18406167,  5783.58358944, 25922.22335941, 24210.23503191,
        48367.40436472,  2902.48541348, 10126.47712093,  4501.74581556,
         7024.4978039 ,  9950.66432529, 39960.83006374, 38606.62063049,
        22841.20004795, 12686.87798794, 23968.93210446,  7634.12229968,
         3217.87843872, 12586.04787745, 12155.12907413, 11995.40029665,
         5751.57378927, 14634.41057566, 18327.60148569,  7836.39806104,
         1869.54992795, 12634.66745433,  7297.7646169 , 39286.42621092,
        10697.35852327,  5047.35489061,  4207.53983373,  7621.18441128,
         4363.60046439,  4340.92683551, 12754.18647768, 11044.62877419,
         6663.57009285, 13691.62819976, 13933.16466495, 10298.4840765 ,
         5627.428811  , 11313.36009395, 14677.74746594,  6715.18683078,
         5532.65263075,  2959.58577862,  6816.38847758,  6329.33865057,
         9945.19211518,  3396.02675837,  6663.57009285, 11569.58378616,
         5832.74115865,  6958.24282836, 28338.65176654,  2143.39187242,
        15210.12657798,  7359.18529478, 11878.52291931,  4803.69348828,
         6448.53199027, 28801.40585541,  3141.93141423,  3869.60870308,
        14468.45819016, 11699.67335085, 42551.5207365 ,  6329.44588966,
         5973.75755593, 24405.47680454,  3652.25045058,  5396.38943049,
         7595.9722575 ,  8081.18079514,  7585.57254919,  5829.2734253 ,
        13009.14868829, 45140.93757169, 14880.01970518, 17901.19501756,
         7198.73640255, 44297.83963238,  5482.92261008, 12319.02174802,
         8157.96593176,  1493.42143643, 10942.89947994, 14622.23079233,
         6453.37593835,  3704.667573  ,  7411.15784108,  5985.09669185,
         7405.84516272,  5983.67720272, 15753.37020375,  7484.61033999,
         8247.72441922,  7443.69433772, 10297.04938402,  3799.54061624,
        11834.07276746, 14685.29445484, 14642.0978928 , 11681.77530016,
         6334.08287971,  3232.86802329,  3694.29269989,  9429.96936784,
        16534.3467573 , 11287.33007526,  5496.30067021,  8010.36238897,
        11760.52952777, 34765.40394039,  6678.27216358, 13458.61793771,
         6263.41450725, 37263.3297775 ,  8833.04860338,  8526.6049887 ,
         9676.09941976, 12892.87437759,  4902.63134063,  9439.73982679,
         2913.85594977,  6873.47580171, 19434.47574902, 45943.52548016,
         6149.38587074,  4971.91139361,  2973.09088067,  1869.54992795,
        10451.16129252,  3126.28847677, 10083.36529952,  5638.98722857,
         8879.48404913, 27165.06819069, 44948.11389039, 17694.30607026,
         7411.15784108, 11012.13715221, 41594.95770438,  9610.51707329]))

In [55]:
# Attributes

In [44]:
n_estimators=regressor.n_estimators_ # The number of estimators as selected by early stopping (if n_iter_no_change is specified). Otherwise it is set to n_estimators.

n_trees_per_iteration= regressor.n_trees_per_iteration_ # The number of trees that are built at each iteration. For regressors, this is always 1.

feature_importance= regressor.feature_importances_ # The impurity-based feature importances.

#oob_improvement=regressor.oob_improvement_ #The improvement in loss on the out-of-bag samples relative to the previous iteration. oob_improvement_[0] is the improvement in loss of the first stage over the init estimator. Only available if subsample < 1.0.
# AttributeError: 'GradientBoostingRegressor' object has no attribute 'oob_improvement_'

#oob_scores=regressor.oob_scores_ #The full history of the loss values on the out-of-bag samples. Only available if subsample < 1.0.
# AttributeError: 'GradientBoostingRegressor' object has no attribute 'oob_scores_'

# oob_score= regressor.oob_score_ # The last value of the loss on the out-of-bag samples. It is the same as oob_scores_[-1]. Only available if subsample < 1.0.
# AttributeError: 'GradientBoostingRegressor' object has no attribute 'oob_score_'

train_score=regressor.train_score_ # The i-th score train_score_[i] is the loss of the model at iteration i on the in-bag sample. If subsample == 1 this is the loss on the training data.

init=regressor.init_ # The estimator that provides the initial predictions. Set via the init argument.

estimators=regressor.estimators_ #The collection of fitted sub-estimators.

n_features_in= regressor.n_features_in_ # Number of features seen during fit.

feature_names_in=regressor.feature_names_in_ #Names of features seen during fit. Defined only when X has feature names that are all strings.

max_features=regressor.max_features_ # The inferred value of max_features.

In [45]:
n_estimators

100

In [46]:
n_trees_per_iteration

1

In [47]:
feature_importance

array([1.25833259e-01, 1.77232144e-01, 1.14039806e-02, 3.62807919e-04,
       6.85167808e-01])

In [48]:
train_score

array([1.20303943e+08, 1.01592366e+08, 8.64219956e+07, 7.41069986e+07,
       6.40992208e+07, 5.59771923e+07, 4.93662758e+07, 4.39834464e+07,
       3.96008703e+07, 3.60380206e+07, 3.31366895e+07, 3.07387658e+07,
       2.87912430e+07, 2.71862732e+07, 2.58796762e+07, 2.47475045e+07,
       2.38511711e+07, 2.31010905e+07, 2.24675107e+07, 2.19534649e+07,
       2.15166914e+07, 2.11445272e+07, 2.08249148e+07, 2.05645641e+07,
       2.03244069e+07, 2.00747586e+07, 1.99158064e+07, 1.97720206e+07,
       1.96550892e+07, 1.95402092e+07, 1.93983434e+07, 1.93140274e+07,
       1.92448031e+07, 1.91420374e+07, 1.90690642e+07, 1.89772307e+07,
       1.89024320e+07, 1.88591802e+07, 1.87917484e+07, 1.87312508e+07,
       1.86915473e+07, 1.86456853e+07, 1.86078538e+07, 1.85740283e+07,
       1.85377532e+07, 1.85019422e+07, 1.84711511e+07, 1.84374898e+07,
       1.84100193e+07, 1.83866711e+07, 1.83311202e+07, 1.83109835e+07,
       1.82602216e+07, 1.82351821e+07, 1.82027859e+07, 1.81756315e+07,
       1.81496870e+07, 1.80720977e+07, 1.80431494e+07, 1.80267116e+07,
       1.79944246e+07, 1.79560291e+07, 1.79238593e+07, 1.78974711e+07,
       1.78664484e+07, 1.78497269e+07, 1.78093751e+07, 1.77833994e+07,
       1.77619689e+07, 1.77270880e+07, 1.76943217e+07, 1.76514567e+07,
       1.75900165e+07, 1.75253250e+07, 1.75077149e+07, 1.74958468e+07,
       1.74460801e+07, 1.74274576e+07, 1.73751768e+07, 1.73470652e+07,
       1.73046920e+07, 1.72899642e+07, 1.72494933e+07, 1.72358249e+07,
       1.72072338e+07, 1.71681996e+07, 1.71355356e+07, 1.71048120e+07,
       1.70818524e+07, 1.70679265e+07, 1.70427208e+07, 1.70308226e+07,
       1.70173755e+07, 1.70058228e+07, 1.69940089e+07, 1.69613092e+07,
       1.69343000e+07, 1.69106317e+07, 1.68817788e+07, 1.68719285e+07])

In [49]:
init

DummyRegressor()

In [50]:
estimators

array([[DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x1A6A291E440)]],
      dtype=object)

In [51]:
n_features_in

5

In [52]:
feature_names_in

array(['age', 'bmi', 'children', 'sex_male', 'smoker_yes'], dtype=object)

In [54]:
max_features

5