In [1]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.3.0-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.3.0-py3-none-win_amd64.whl (69.5 MB)
   ---------------------------------------- 0.0/69.5 MB ? eta -:--:--
   - -------------------------------------- 3.1/69.5 MB 21.6 MB/s eta 0:00:04
   ----- ---------------------------------- 9.7/69.5 MB 26.8 MB/s eta 0:00:03
   --------- ------------------------------ 17.0/69.5 MB 29.6 MB/s eta 0:00:02
   ------------- -------------------------- 23.9/69.5 MB 30.3 MB/s eta 0:00:02
   ----------------- ---------------------- 30.9/69.5 MB 31.2 MB/s eta 0:00:02
   -------------------- ------------------- 36.4/69.5 MB 30.2 MB/s eta 0:00:02
   ------------------------ --------------- 41.9/69.5 MB 29.5 MB/s eta 0:00:01
   ------------------------- -------------- 44.3/69.5 MB 27.3 MB/s eta 0:00:01
   --------------------------- ------------ 47.4/69.5 MB 25.7 MB/s eta 0:00:01
   ----------------------------- ---------- 50.9/69.5 MB 24.9 MB/s eta 0:00:01
   ------------------------------- -------- 55.3/69.5 MB 24.5 MB/s eta 0:00:01
   ---------------------------------- ----- 60.0/69.5 MB 24.3 MB/s eta 0:00:01
   ------------------------------------- -- 65.0/69.5 MB 24.1 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 24.0 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 24.0 MB/s eta 0:00:01
   ---------------------------------------- 69.5/69.5 MB 21.9 MB/s  0:00:03
Installing collected packages: xgboost
Successfully installed xgboost-3.3.0

In [2]:
import xgboost

In [3]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset, drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [5]:
dataset=dataset.astype(int)
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(independent,dependent, test_size=0.20, random_state=0)

In [50]:
from xgboost import XGBRegressor
regressor=XGBRegressor(n_estimators=30, learning_rate=0.1, random_state=0)
regressor=regressor.fit(X_train, Y_train)

In [51]:
Y_pred=regressor.predict(X_test)
Y_pred

array([11790.971 , 10878.975 , 43159.746 , 13336.524 ,  9404.994 ,
       11346.348 ,  2645.9585, 12414.446 ,  7443.2686,  6045.0024,
        7062.7036, 15075.282 , 10780.422 ,  6409.1724, 19965.174 ,
       13351.18  , 13725.6   ,  5295.132 ,  7505.0244, 33643.402 ,
       23456.645 , 14141.3955, 11866.277 , 24298.256 ,  4865.3335,
        5125.371 ,  5578.8438,  8105.9004,  4298.967 , 10168.853 ,
        7713.339 , 45906.312 , 14133.689 , 11834.588 , 17341.225 ,
        4735.7695,  9752.983 , 35189.22  , 38471.42  ,  4653.0693,
       11078.918 ,  4496.7856, 19785.256 , 45920.938 , 36190.746 ,
        5326.8477, 14830.976 ,  6737.5254,  5456.031 , 12385.911 ,
        4343.947 , 10133.454 , 25719.16  , 43072.977 , 11198.237 ,
        4899.488 ,  3913.613 , 12449.665 ,  9329.148 , 15799.244 ,
        2939.521 , 42431.08  , 16860.613 , 13741.417 , 12425.745 ,
        9752.429 , 33643.402 , 38626.535 ,  5327.541 , 10703.684 ,
       14464.964 , 12328.854 , 19532.35  , 14109.183 , 14159.099 ,
       14457.456 ,  9077.928 , 10168.853 , 19357.725 , 45920.938 ,
       11985.997 , 44220.42  ,  3774.7095, 10692.043 , 38756.68  ,
       19205.775 ,  4552.6963,  4155.306 , 15108.317 , 37504.973 ,
        5620.0083, 12262.902 ,  3660.2446, 11160.407 ,  6174.754 ,
        5961.9663, 41042.535 , 40348.65  ,  6189.9277, 11156.409 ,
        4484.4717,  6249.518 ,  7708.136 , 38228.6   , 29723.158 ,
        6332.58  , 11278.424 ,  4812.753 , 11640.629 , 44442.855 ,
       12799.647 ,  5432.4185, 11176.866 , 33899.117 , 49862.93  ,
        7448.32  ,  2984.273 , 12449.665 , 25010.934 ,  9204.705 ,
       40265.273 , 12017.382 , 13318.713 ,  5930.4575, 11129.177 ,
        6351.333 , 24555.928 , 26071.021 , 45906.312 ,  3533.0164,
       11668.013 ,  5500.54  ,  7030.9473,  8490.649 , 39034.707 ,
       38430.03  , 23360.484 , 12278.778 , 23283.955 ,  6444.9824,
        3562.4456, 12789.529 , 12084.042 , 12305.347 ,  6131.335 ,
       14040.058 , 25040.084 ,  6566.079 ,  2458.3438, 12746.616 ,
        6959.854 , 38395.254 , 10406.121 ,  5230.8677,  4745.329 ,
        7556.355 ,  5405.987 ,  5019.9785, 13351.18  , 11023.004 ,
        8879.367 , 13336.524 , 14148.911 ,  9331.8125,  6144.836 ,
        6456.3794, 14437.816 ,  6256.909 ,  5576.523 ,  3942.641 ,
        8540.814 ,  7308.7036,  9722.457 ,  4242.7803,  9004.136 ,
        6389.737 ,  6337.4336,  8136.268 , 25747.98  ,  2589.2153,
       14070.822 ,  7621.13  , 11586.096 ,  6402.756 ,  7191.994 ,
       26937.55  ,  3774.7095,  3964.5693, 14235.765 , 11223.1875,
       41139.3   ,  7439.5786,  6079.968 , 24990.707 ,  4102.7964,
        4402.083 ,  7712.2266,  7019.143 ,  7166.662 ,  5688.1494,
       12317.193 , 44607.47  , 14302.692 , 19039.016 ,  7678.7954,
       41443.68  ,  6644.6475, 11872.915 ,  8355.581 ,  3145.9514,
       11071.898 , 14103.146 ,  7433.1577,  5849.0815,  6991.178 ,
        4997.8   ,  6708.802 ,  7580.6577, 15012.535 ,  7426.8823,
        9910.05  ,  7467.4526, 11278.379 ,  4696.609 , 12185.876 ,
       14133.689 , 20688.406 , 12717.362 ,  7262.6455,  4262.0996,
        3342.9224,  8458.977 , 17483.15  ,  4981.5615,  5245.9546,
        8093.301 , 12785.448 , 33899.117 ,  6794.1914, 12799.647 ,
        6858.6113, 35663.75  ,  8467.105 ,  8635.833 ,  9573.056 ,
       12307.249 ,  5701.089 ,  9119.257 ,  2774.6543,  6898.05  ,
       20528.37  , 44607.47  ,  5441.068 ,  4741.8784,  3100.1494,
        2697.1091,  9252.968 ,  3672.2598,  7274.234 ,  7344.859 ,
        8858.912 , 25794.504 , 44607.47  , 17116.242 ,  6991.178 ,
       11156.409 , 45135.34  ,  9551.953 ], dtype=float32)

In [52]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test, Y_pred)
r_score

0.8903524279594421

In [53]:
pred_test=regressor.predict([[52,30.2,1,1,0]])
pred_test

array([11790.971], dtype=float32)

In [54]:
pred_test=regressor.predict([[89,30.2,1,1,0]])
pred_test

array([16898.63], dtype=float32)