In [2]:
!pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in c:\anaconda3\lib\site-packages (from lightgbm) (2.3.5)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from lightgbm) (1.16.3)
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 14.5 MB/s  0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

In [4]:
import lightgbm

In [5]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [6]:
dataset=pd.get_dummies(dataset, drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
dataset=dataset.astype(int)
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [8]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(independent,dependent, test_size=0.20, random_state=0)

In [10]:
from lightgbm import LGBMRegressor
regressor=LGBMRegressor(n_estimators=100, learning_rate=0.1, max_depth=5, random_state=0)
regressor=regressor.fit(X_train, Y_train)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000578 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 93
[LightGBM] [Info] Number of data points in the train set: 1070, number of used features: 5
[LightGBM] [Info] Start training from score 13200.691589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [11]:
regressor

LGBMRegressor(max_depth=5, random_state=0)

In [13]:
Y_pred=regressor.predict(X_test)
Y_pred

array([11757.79736096, 11272.70037396, 45274.95556994, 14094.31726233,
       10330.07837154,  7479.98471611,  1920.1910872 , 13514.48611592,
        7197.47325772,  5035.0656867 ,  6060.45798424, 14243.72716588,
       10550.44044213,  7145.53632561, 19496.51848472, 11846.45439469,
       13673.93567104,  4895.36269875,  7943.26930343, 34903.80871294,
       23535.8408637 , 13915.91756038, 12066.65825897, 26026.16502018,
        3683.24169276,  5599.38197638,  5886.8776412 ,  7361.13633255,
        3027.97541791, 10508.36871805,  6839.32977478, 49048.37487653,
       16667.68403616, 13637.04839404, 18419.5609255 ,  4339.49986859,
        9243.72533373, 36848.53410591, 38569.80190235,  3466.92807884,
        5955.06678654,  5067.49364583, 21414.67327078, 46883.57276056,
       37222.31403583,  6071.46969856, 14557.43062397,  6582.63436289,
        5531.12549289, 11469.5138129 ,  3190.45847841,  7381.85766697,
       24955.81742196, 46506.73583705, 11832.37075338,  4025.63448021,
        2848.87649278, 11564.69738824,  9171.43933802, 16405.70132875,
        2469.79037357, 46210.73920179, 17242.13579536, 13354.23594118,
       13360.4677676 ,  8468.1087836 , 34127.55356652, 40187.70210428,
        5365.46654353,  9246.7163163 , 15021.40213493, 12310.53593092,
       18307.93757472, 14763.12989224, 15326.31676698, 14166.33698789,
        9328.21740415, 10615.23926379, 18022.90970547, 48024.14759646,
       11126.02666857, 46785.50906448,  3528.55894195, 10004.92942757,
       39359.85646521, 18608.31923843,  4669.87908278,  3740.51450618,
       15447.39313078, 38561.64684851,  5689.48072638, 12838.42464046,
        3315.65137719, 12574.35541406,  6082.25094044,  5635.70494522,
       46931.0455562 , 41316.8560742 ,  6079.79403787, 10557.9631017 ,
        4203.76717692,  5962.6008563 ,  7813.12469184, 38247.58289929,
       26509.91838076,  4914.05189552, 10461.42499505,  3790.94994528,
       12031.56721693, 46789.19381973, 12446.83212373,  4902.10066578,
       11043.29881852, 34202.04506901, 48172.37710146,  7109.50115418,
        2926.83239048, 11564.69738824, 18748.74794657,  9448.33613011,
       41999.63949421, 12243.61208625, 12576.84282664,  5204.52936172,
       10872.47328349,  5860.76967146, 25501.78091097, 25122.85029531,
       49150.53492723,  2441.92641393, 11507.36248573,  5548.50851246,
        6692.43202576,  9818.38082174, 40608.85705766, 39524.67003425,
       23324.86254633, 12239.98531449, 23874.00015344,  7346.44419767,
        3256.08382025, 13340.29733708, 11346.14713288, 12401.7495955 ,
        5412.93756583, 14002.5966432 , 18711.25085537,  8591.40066602,
        2070.56174121, 12760.03120536,  7090.69791779, 39676.64666002,
        9931.63019569,  4961.48962431,  5115.96819287,  7516.24600062,
        4632.92484585,  4603.51370469, 11846.45439469,  9918.00739661,
        5530.71827464, 14028.22177972, 14287.03772051,  8157.25269576,
        4565.09544426,  6575.05094989, 14982.91262055,  6345.93706176,
        5393.17042438,  3256.95331834,  7175.75621244,  6966.65096863,
       10857.60072295,  3195.01231187,  7212.01467358,  7126.99721632,
        6084.29328736,  7414.95492242, 27342.07136739,  1530.92149368,
       16021.66109751,  6711.86197849, 11425.19925067,  5236.1078967 ,
        6866.92077086, 28818.70587274,  3349.36558503,  3767.6048568 ,
       12801.0938432 , 11084.22132959, 41979.7967186 ,  7484.43800292,
        5011.70306178, 23567.24313229,  2951.19700839,  5211.81685304,
        7943.26930343,  7080.32939139,  6865.01862433,  5092.44799128,
       12599.06755156, 46864.93218663, 15185.74515328, 18664.97044935,
        7285.4478716 , 43380.71688049,  4509.97124477, 11741.36713597,
        7840.55988578,  2339.3165065 , 10777.9101612 , 13678.68378007,
        6834.01510056,  4359.96708858,  6516.55040892,  6157.9961968 ,
        6488.41890684,  6850.59863231, 15590.84493106,  8010.3488581 ,
        8067.63710347,  7885.36727441, 10608.51520315,  4274.06289487,
       11915.74982476, 15253.48703063, 16366.6620418 , 12443.16120438,
        6555.79441836,  2139.92747152,  3493.00115243,  8430.04199764,
       14252.1230981 ,  7308.65416668,  5697.79536529,  7863.65868675,
       13672.40279934, 34766.11007346,  6291.35210665, 12756.49141119,
        6346.31340816, 38592.99380405,  9107.82532816,  7824.99423128,
       10075.93760239, 11419.48824582,  5572.44064463,  9357.05704824,
        3503.81725994,  6787.8300112 , 19283.39654269, 46511.14908484,
        5538.50169031,  4772.19959839,  3192.410064  ,  2070.56174121,
        9591.26661711,  2978.10391985,  6236.22652165,  6382.41870237,
        7891.598537  , 25667.80388663, 46429.78260027, 17464.06069894,
        6516.55040892, 10748.24453713, 43624.62075674,  9480.74977295])

In [14]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test, Y_pred)
r_score

0.8960563107644208

In [15]:
pred_test=regressor.predict([[52,30.2,1,1,0]])
pred_test

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

array([11757.79736096])