In [2]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [4]:
 dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
1
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['absolute_error','poisson'], 'max_features': ['sqrt','log2'], 'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)

# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [10]:
 # print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)
# print classification report
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'absolute_error', 'max_features': 'sqrt', 'n_estimators': 100}: 0.8741552543727451

In [11]:
table=pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.065679,0.004789,0.003275,0.001691,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.758739,0.742818,0.821021,0.787076,0.765409,0.775013,0.027040,7
1,0.766876,0.045227,0.016224,0.001064,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.804891,0.780172,0.838740,0.820575,0.762771,0.801430,0.027265,1
2,0.066967,0.011776,0.002348,0.000820,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.776355,0.733902,0.812205,0.808355,0.746430,0.775449,0.031632,6
3,0.806075,0.015731,0.015515,0.001382,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.803643,0.774508,0.835185,0.825171,0.758365,0.799374,0.029210,4
4,0.032666,0.001424,0.002759,0.000251,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.759084,0.744685,0.820509,0.799710,0.742353,0.773268,0.031320,8
5,0.310336,0.009577,0.014660,0.001376,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.797533,0.771311,0.834762,0.829019,0.765383,0.799602,0.028556,3
6,0.034277,0.001637,0.003583,0.000543,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.783539,0.736411,0.818190,0.817759,0.744964,0.780173,0.034711,5
7,0.231148,0.006048,0.009949,0.001396,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.806319,0.770250,0.833410,0.835021,0.759494,0.800899,0.031319,2

In [13]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 52
BMI: 30
Children: 1
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 0

In [14]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[14546.1916378]